//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDCardSummChecker.ZRepSrv {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://Piskov.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://Piskov.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XmlCheckRecive", Namespace="http://Piskov.org/")]
    [System.SerializableAttribute()]
    public partial class XmlCheckRecive : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal CardField;
        
        private System.DateTime DtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Card {
            get {
                return this.CardField;
            }
            set {
                if ((this.CardField.Equals(value) != true)) {
                    this.CardField = value;
                    this.RaisePropertyChanged("Card");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Dt {
            get {
                return this.DtField;
            }
            set {
                if ((this.DtField.Equals(value) != true)) {
                    this.DtField = value;
                    this.RaisePropertyChanged("Dt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Piskov.org/", ConfigurationName="ZRepSrv.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name GetZReportsResult from namespace http://Piskov.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Piskov.org/GetZReports", ReplyAction="*")]
        PDCardSummChecker.ZRepSrv.GetZReportsResponse GetZReports(PDCardSummChecker.ZRepSrv.GetZReportsRequest request);
        
        // CODEGEN: Generating message contract since element name GetKKmsSumFromStartLifeResult from namespace http://Piskov.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Piskov.org/GetKKmsSumFromStartLife", ReplyAction="*")]
        PDCardSummChecker.ZRepSrv.GetKKmsSumFromStartLifeResponse GetKKmsSumFromStartLife(PDCardSummChecker.ZRepSrv.GetKKmsSumFromStartLifeRequest request);
        
        // CODEGEN: Generating message contract since element name TestResult from namespace http://Piskov.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Piskov.org/Test", ReplyAction="*")]
        PDCardSummChecker.ZRepSrv.TestResponse Test(PDCardSummChecker.ZRepSrv.TestRequest request);
        
        // CODEGEN: Generating message contract since element name Message from namespace http://Piskov.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Piskov.org/AddError", ReplyAction="*")]
        PDCardSummChecker.ZRepSrv.AddErrorResponse AddError(PDCardSummChecker.ZRepSrv.AddErrorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Piskov.org/ConvertData", ReplyAction="*")]
        void ConvertData(int UnDepNumber);
        
        // CODEGEN: Generating message contract since element name Data from namespace http://Piskov.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Piskov.org/AddHamsterCheck", ReplyAction="*")]
        PDCardSummChecker.ZRepSrv.AddHamsterCheckResponse AddHamsterCheck(PDCardSummChecker.ZRepSrv.AddHamsterCheckRequest request);
        
        // CODEGEN: Generating message contract since element name Data from namespace http://Piskov.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Piskov.org/AddHamsterChecks", ReplyAction="*")]
        PDCardSummChecker.ZRepSrv.AddHamsterChecksResponse AddHamsterChecks(PDCardSummChecker.ZRepSrv.AddHamsterChecksRequest request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://Piskov.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Piskov.org/CopyLogFile", ReplyAction="*")]
        PDCardSummChecker.ZRepSrv.CopyLogFileResponse CopyLogFile(PDCardSummChecker.ZRepSrv.CopyLogFileRequest request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://Piskov.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Piskov.org/CopyCheckFile", ReplyAction="*")]
        PDCardSummChecker.ZRepSrv.CopyCheckFileResponse CopyCheckFile(PDCardSummChecker.ZRepSrv.CopyCheckFileRequest request);
        
        // CODEGEN: Generating message contract since element name mPaymentCardInfo from namespace http://Piskov.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Piskov.org/AddPaymentCardInfo", ReplyAction="*")]
        PDCardSummChecker.ZRepSrv.AddPaymentCardInfoResponse AddPaymentCardInfo(PDCardSummChecker.ZRepSrv.AddPaymentCardInfoRequest request);
        
        // CODEGEN: Generating message contract since element name GetPaymentCardInfoReportResult from namespace http://Piskov.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Piskov.org/GetPaymentCardInfoReport", ReplyAction="*")]
        PDCardSummChecker.ZRepSrv.GetPaymentCardInfoReportResponse GetPaymentCardInfoReport(PDCardSummChecker.ZRepSrv.GetPaymentCardInfoReportRequest request);
        
        // CODEGEN: Generating message contract since element name Rep from namespace http://Piskov.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Piskov.org/AddZRep2", ReplyAction="*")]
        PDCardSummChecker.ZRepSrv.AddZRep2Response AddZRep2(PDCardSummChecker.ZRepSrv.AddZRep2Request request);
        
        // CODEGEN: Generating message contract since element name ZInfo from namespace http://Piskov.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Piskov.org/AddZRep", ReplyAction="*")]
        PDCardSummChecker.ZRepSrv.AddZRepResponse AddZRep(PDCardSummChecker.ZRepSrv.AddZRepRequest request);
        
        // CODEGEN: Generating message contract since element name GetZRepResult from namespace http://Piskov.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Piskov.org/GetZRep", ReplyAction="*")]
        PDCardSummChecker.ZRepSrv.GetZRepResponse GetZRep(PDCardSummChecker.ZRepSrv.GetZRepRequest request);
        
        // CODEGEN: Generating message contract since element name kkmnum from namespace http://Piskov.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Piskov.org/GetCheckCountFromEklz", ReplyAction="*")]
        PDCardSummChecker.ZRepSrv.GetCheckCountFromEklzResponse GetCheckCountFromEklz(PDCardSummChecker.ZRepSrv.GetCheckCountFromEklzRequest request);
        
        // CODEGEN: Generating message contract since element name GetZRepStringsResult from namespace http://Piskov.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Piskov.org/GetZRepStrings", ReplyAction="*")]
        PDCardSummChecker.ZRepSrv.GetZRepStringsResponse GetZRepStrings(PDCardSummChecker.ZRepSrv.GetZRepStringsRequest request);
        
        // CODEGEN: Generating message contract since element name GetZRepStringsTestResult from namespace http://Piskov.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Piskov.org/GetZRepStringsTest", ReplyAction="*")]
        PDCardSummChecker.ZRepSrv.GetZRepStringsTestResponse GetZRepStringsTest(PDCardSummChecker.ZRepSrv.GetZRepStringsTestRequest request);
        
        // CODEGEN: Generating message contract since element name GetZRep3Result from namespace http://Piskov.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Piskov.org/GetZRep3", ReplyAction="*")]
        PDCardSummChecker.ZRepSrv.GetZRep3Response GetZRep3(PDCardSummChecker.ZRepSrv.GetZRep3Request request);
        
        // CODEGEN: Generating message contract since element name GetZRep2Result from namespace http://Piskov.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Piskov.org/GetZRep2", ReplyAction="*")]
        PDCardSummChecker.ZRepSrv.GetZRep2Response GetZRep2(PDCardSummChecker.ZRepSrv.GetZRep2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Piskov.org/DepIsWhite", ReplyAction="*")]
        int DepIsWhite(int _DepNum);
        
        // CODEGEN: Generating message contract since element name GetChecksByDofBandDepResult from namespace http://Piskov.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Piskov.org/GetChecksByDofBandDep", ReplyAction="*")]
        PDCardSummChecker.ZRepSrv.GetChecksByDofBandDepResponse GetChecksByDofBandDep(PDCardSummChecker.ZRepSrv.GetChecksByDofBandDepRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllDepsResult from namespace http://Piskov.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Piskov.org/GetAllDeps", ReplyAction="*")]
        PDCardSummChecker.ZRepSrv.GetAllDepsResponse GetAllDeps(PDCardSummChecker.ZRepSrv.GetAllDepsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZReportsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZReports", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.GetZReportsRequestBody Body;
        
        public GetZReportsRequest() {
        }
        
        public GetZReportsRequest(PDCardSummChecker.ZRepSrv.GetZReportsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class GetZReportsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime BusinessDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int DepNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int TermNum;
        
        public GetZReportsRequestBody() {
        }
        
        public GetZReportsRequestBody(System.DateTime BusinessDate, int DepNum, int TermNum) {
            this.BusinessDate = BusinessDate;
            this.DepNum = DepNum;
            this.TermNum = TermNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZReportsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZReportsResponse", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.GetZReportsResponseBody Body;
        
        public GetZReportsResponse() {
        }
        
        public GetZReportsResponse(PDCardSummChecker.ZRepSrv.GetZReportsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class GetZReportsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetZReportsResult;
        
        public GetZReportsResponseBody() {
        }
        
        public GetZReportsResponseBody(string GetZReportsResult) {
            this.GetZReportsResult = GetZReportsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetKKmsSumFromStartLifeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetKKmsSumFromStartLife", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.GetKKmsSumFromStartLifeRequestBody Body;
        
        public GetKKmsSumFromStartLifeRequest() {
        }
        
        public GetKKmsSumFromStartLifeRequest(PDCardSummChecker.ZRepSrv.GetKKmsSumFromStartLifeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetKKmsSumFromStartLifeRequestBody {
        
        public GetKKmsSumFromStartLifeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetKKmsSumFromStartLifeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetKKmsSumFromStartLifeResponse", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.GetKKmsSumFromStartLifeResponseBody Body;
        
        public GetKKmsSumFromStartLifeResponse() {
        }
        
        public GetKKmsSumFromStartLifeResponse(PDCardSummChecker.ZRepSrv.GetKKmsSumFromStartLifeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class GetKKmsSumFromStartLifeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PDCardSummChecker.ZRepSrv.ArrayOfInt GetKKmsSumFromStartLifeResult;
        
        public GetKKmsSumFromStartLifeResponseBody() {
        }
        
        public GetKKmsSumFromStartLifeResponseBody(PDCardSummChecker.ZRepSrv.ArrayOfInt GetKKmsSumFromStartLifeResult) {
            this.GetKKmsSumFromStartLifeResult = GetKKmsSumFromStartLifeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Test", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.TestRequestBody Body;
        
        public TestRequest() {
        }
        
        public TestRequest(PDCardSummChecker.ZRepSrv.TestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestRequestBody {
        
        public TestRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestResponse", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.TestResponseBody Body;
        
        public TestResponse() {
        }
        
        public TestResponse(PDCardSummChecker.ZRepSrv.TestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class TestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestResult;
        
        public TestResponseBody() {
        }
        
        public TestResponseBody(string TestResult) {
            this.TestResult = TestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddErrorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddError", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.AddErrorRequestBody Body;
        
        public AddErrorRequest() {
        }
        
        public AddErrorRequest(PDCardSummChecker.ZRepSrv.AddErrorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class AddErrorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Message;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int _DepNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Term;
        
        public AddErrorRequestBody() {
        }
        
        public AddErrorRequestBody(string Message, int _DepNum, int Term) {
            this.Message = Message;
            this._DepNum = _DepNum;
            this.Term = Term;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddErrorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddErrorResponse", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.AddErrorResponseBody Body;
        
        public AddErrorResponse() {
        }
        
        public AddErrorResponse(PDCardSummChecker.ZRepSrv.AddErrorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddErrorResponseBody {
        
        public AddErrorResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddHamsterCheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddHamsterCheck", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.AddHamsterCheckRequestBody Body;
        
        public AddHamsterCheckRequest() {
        }
        
        public AddHamsterCheckRequest(PDCardSummChecker.ZRepSrv.AddHamsterCheckRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class AddHamsterCheckRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Data;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int UnDepNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int DepNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FileName;
        
        public AddHamsterCheckRequestBody() {
        }
        
        public AddHamsterCheckRequestBody(string Data, int UnDepNumber, int DepNumber, string FileName) {
            this.Data = Data;
            this.UnDepNumber = UnDepNumber;
            this.DepNumber = DepNumber;
            this.FileName = FileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddHamsterCheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddHamsterCheckResponse", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.AddHamsterCheckResponseBody Body;
        
        public AddHamsterCheckResponse() {
        }
        
        public AddHamsterCheckResponse(PDCardSummChecker.ZRepSrv.AddHamsterCheckResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class AddHamsterCheckResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddHamsterCheckResult;
        
        public AddHamsterCheckResponseBody() {
        }
        
        public AddHamsterCheckResponseBody(string AddHamsterCheckResult) {
            this.AddHamsterCheckResult = AddHamsterCheckResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddHamsterChecksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddHamsterChecks", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.AddHamsterChecksRequestBody Body;
        
        public AddHamsterChecksRequest() {
        }
        
        public AddHamsterChecksRequest(PDCardSummChecker.ZRepSrv.AddHamsterChecksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class AddHamsterChecksRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement Data;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int UnDepNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int DepNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FileName;
        
        public AddHamsterChecksRequestBody() {
        }
        
        public AddHamsterChecksRequestBody(System.Xml.Linq.XElement Data, int UnDepNumber, int DepNumber, string FileName) {
            this.Data = Data;
            this.UnDepNumber = UnDepNumber;
            this.DepNumber = DepNumber;
            this.FileName = FileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddHamsterChecksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddHamsterChecksResponse", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.AddHamsterChecksResponseBody Body;
        
        public AddHamsterChecksResponse() {
        }
        
        public AddHamsterChecksResponse(PDCardSummChecker.ZRepSrv.AddHamsterChecksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class AddHamsterChecksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddHamsterChecksResult;
        
        public AddHamsterChecksResponseBody() {
        }
        
        public AddHamsterChecksResponseBody(string AddHamsterChecksResult) {
            this.AddHamsterChecksResult = AddHamsterChecksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CopyLogFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CopyLogFile", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.CopyLogFileRequestBody Body;
        
        public CopyLogFileRequest() {
        }
        
        public CopyLogFileRequest(PDCardSummChecker.ZRepSrv.CopyLogFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class CopyLogFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] data;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long OriginalDataLenght;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int UnDepNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int DepNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int FType;
        
        public CopyLogFileRequestBody() {
        }
        
        public CopyLogFileRequestBody(byte[] data, long OriginalDataLenght, string FName, int UnDepNumber, int DepNumber, int FType) {
            this.data = data;
            this.OriginalDataLenght = OriginalDataLenght;
            this.FName = FName;
            this.UnDepNumber = UnDepNumber;
            this.DepNumber = DepNumber;
            this.FType = FType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CopyLogFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CopyLogFileResponse", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.CopyLogFileResponseBody Body;
        
        public CopyLogFileResponse() {
        }
        
        public CopyLogFileResponse(PDCardSummChecker.ZRepSrv.CopyLogFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class CopyLogFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PDiscountCard.ZRepSrv.CopyCheckFileResult CopyLogFileResult;
        
        public CopyLogFileResponseBody() {
        }
        
        public CopyLogFileResponseBody(PDiscountCard.ZRepSrv.CopyCheckFileResult CopyLogFileResult) {
            this.CopyLogFileResult = CopyLogFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CopyCheckFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CopyCheckFile", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.CopyCheckFileRequestBody Body;
        
        public CopyCheckFileRequest() {
        }
        
        public CopyCheckFileRequest(PDCardSummChecker.ZRepSrv.CopyCheckFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class CopyCheckFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] data;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long OriginalDataLenght;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int UnDepNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int DepNumber;
        
        public CopyCheckFileRequestBody() {
        }
        
        public CopyCheckFileRequestBody(byte[] data, long OriginalDataLenght, string FName, int UnDepNumber, int DepNumber) {
            this.data = data;
            this.OriginalDataLenght = OriginalDataLenght;
            this.FName = FName;
            this.UnDepNumber = UnDepNumber;
            this.DepNumber = DepNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CopyCheckFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CopyCheckFileResponse", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.CopyCheckFileResponseBody Body;
        
        public CopyCheckFileResponse() {
        }
        
        public CopyCheckFileResponse(PDCardSummChecker.ZRepSrv.CopyCheckFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class CopyCheckFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PDiscountCard.ZRepSrv.CopyCheckFileResult CopyCheckFileResult;
        
        public CopyCheckFileResponseBody() {
        }
        
        public CopyCheckFileResponseBody(PDiscountCard.ZRepSrv.CopyCheckFileResult CopyCheckFileResult) {
            this.CopyCheckFileResult = CopyCheckFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPaymentCardInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPaymentCardInfo", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.AddPaymentCardInfoRequestBody Body;
        
        public AddPaymentCardInfoRequest() {
        }
        
        public AddPaymentCardInfoRequest(PDCardSummChecker.ZRepSrv.AddPaymentCardInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class AddPaymentCardInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PDiscountCard.ZRepSrv.PaymentCard mPaymentCardInfo;
        
        public AddPaymentCardInfoRequestBody() {
        }
        
        public AddPaymentCardInfoRequestBody(PDiscountCard.ZRepSrv.PaymentCard mPaymentCardInfo) {
            this.mPaymentCardInfo = mPaymentCardInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPaymentCardInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPaymentCardInfoResponse", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.AddPaymentCardInfoResponseBody Body;
        
        public AddPaymentCardInfoResponse() {
        }
        
        public AddPaymentCardInfoResponse(PDCardSummChecker.ZRepSrv.AddPaymentCardInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class AddPaymentCardInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddPaymentCardInfoResult;
        
        public AddPaymentCardInfoResponseBody() {
        }
        
        public AddPaymentCardInfoResponseBody(bool AddPaymentCardInfoResult) {
            this.AddPaymentCardInfoResult = AddPaymentCardInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPaymentCardInfoReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPaymentCardInfoReport", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.GetPaymentCardInfoReportRequestBody Body;
        
        public GetPaymentCardInfoReportRequest() {
        }
        
        public GetPaymentCardInfoReportRequest(PDCardSummChecker.ZRepSrv.GetPaymentCardInfoReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class GetPaymentCardInfoReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UndepNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime Bdate;
        
        public GetPaymentCardInfoReportRequestBody() {
        }
        
        public GetPaymentCardInfoReportRequestBody(int UndepNum, System.DateTime Bdate) {
            this.UndepNum = UndepNum;
            this.Bdate = Bdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPaymentCardInfoReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPaymentCardInfoReportResponse", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.GetPaymentCardInfoReportResponseBody Body;
        
        public GetPaymentCardInfoReportResponse() {
        }
        
        public GetPaymentCardInfoReportResponse(PDCardSummChecker.ZRepSrv.GetPaymentCardInfoReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class GetPaymentCardInfoReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PDiscountCard.ZRepSrv.PaymentCard[] GetPaymentCardInfoReportResult;
        
        public GetPaymentCardInfoReportResponseBody() {
        }
        
        public GetPaymentCardInfoReportResponseBody(PDiscountCard.ZRepSrv.PaymentCard[] GetPaymentCardInfoReportResult) {
            this.GetPaymentCardInfoReportResult = GetPaymentCardInfoReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddZRep2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddZRep2", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.AddZRep2RequestBody Body;
        
        public AddZRep2Request() {
        }
        
        public AddZRep2Request(PDCardSummChecker.ZRepSrv.AddZRep2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class AddZRep2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PDiscountCard.ZRepSrv.TblZReports2 Rep;
        
        public AddZRep2RequestBody() {
        }
        
        public AddZRep2RequestBody(PDiscountCard.ZRepSrv.TblZReports2 Rep) {
            this.Rep = Rep;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddZRep2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddZRep2Response", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.AddZRep2ResponseBody Body;
        
        public AddZRep2Response() {
        }
        
        public AddZRep2Response(PDCardSummChecker.ZRepSrv.AddZRep2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class AddZRep2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddZRep2Result;
        
        public AddZRep2ResponseBody() {
        }
        
        public AddZRep2ResponseBody(string AddZRep2Result) {
            this.AddZRep2Result = AddZRep2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddZRepRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddZRep", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.AddZRepRequestBody Body;
        
        public AddZRepRequest() {
        }
        
        public AddZRepRequest(PDCardSummChecker.ZRepSrv.AddZRepRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class AddZRepRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PDiscountCard.ZRepSrv.ZReportInfo ZInfo;
        
        public AddZRepRequestBody() {
        }
        
        public AddZRepRequestBody(PDiscountCard.ZRepSrv.ZReportInfo ZInfo) {
            this.ZInfo = ZInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddZRepResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddZRepResponse", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.AddZRepResponseBody Body;
        
        public AddZRepResponse() {
        }
        
        public AddZRepResponse(PDCardSummChecker.ZRepSrv.AddZRepResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class AddZRepResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddZRepResult;
        
        public AddZRepResponseBody() {
        }
        
        public AddZRepResponseBody(string AddZRepResult) {
            this.AddZRepResult = AddZRepResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZRepRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZRep", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.GetZRepRequestBody Body;
        
        public GetZRepRequest() {
        }
        
        public GetZRepRequest(PDCardSummChecker.ZRepSrv.GetZRepRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class GetZRepRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime BusinessDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int UnDepNum;
        
        public GetZRepRequestBody() {
        }
        
        public GetZRepRequestBody(System.DateTime BusinessDate, int UnDepNum) {
            this.BusinessDate = BusinessDate;
            this.UnDepNum = UnDepNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZRepResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZRepResponse", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.GetZRepResponseBody Body;
        
        public GetZRepResponse() {
        }
        
        public GetZRepResponse(PDCardSummChecker.ZRepSrv.GetZRepResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class GetZRepResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PDiscountCard.ZRepSrv.ZReportInfo GetZRepResult;
        
        public GetZRepResponseBody() {
        }
        
        public GetZRepResponseBody(PDiscountCard.ZRepSrv.ZReportInfo GetZRepResult) {
            this.GetZRepResult = GetZRepResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCheckCountFromEklzRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCheckCountFromEklz", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.GetCheckCountFromEklzRequestBody Body;
        
        public GetCheckCountFromEklzRequest() {
        }
        
        public GetCheckCountFromEklzRequest(PDCardSummChecker.ZRepSrv.GetCheckCountFromEklzRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class GetCheckCountFromEklzRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string kkmnum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int repnum2;
        
        public GetCheckCountFromEklzRequestBody() {
        }
        
        public GetCheckCountFromEklzRequestBody(string kkmnum, int repnum2) {
            this.kkmnum = kkmnum;
            this.repnum2 = repnum2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCheckCountFromEklzResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCheckCountFromEklzResponse", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.GetCheckCountFromEklzResponseBody Body;
        
        public GetCheckCountFromEklzResponse() {
        }
        
        public GetCheckCountFromEklzResponse(PDCardSummChecker.ZRepSrv.GetCheckCountFromEklzResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class GetCheckCountFromEklzResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetCheckCountFromEklzResult;
        
        public GetCheckCountFromEklzResponseBody() {
        }
        
        public GetCheckCountFromEklzResponseBody(int GetCheckCountFromEklzResult) {
            this.GetCheckCountFromEklzResult = GetCheckCountFromEklzResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZRepStringsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZRepStrings", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.GetZRepStringsRequestBody Body;
        
        public GetZRepStringsRequest() {
        }
        
        public GetZRepStringsRequest(PDCardSummChecker.ZRepSrv.GetZRepStringsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class GetZRepStringsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime BusinessDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int DepNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Term;
        
        public GetZRepStringsRequestBody() {
        }
        
        public GetZRepStringsRequestBody(System.DateTime BusinessDate, int DepNum, int Term) {
            this.BusinessDate = BusinessDate;
            this.DepNum = DepNum;
            this.Term = Term;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZRepStringsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZRepStringsResponse", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.GetZRepStringsResponseBody Body;
        
        public GetZRepStringsResponse() {
        }
        
        public GetZRepStringsResponse(PDCardSummChecker.ZRepSrv.GetZRepStringsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class GetZRepStringsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PDCardSummChecker.ZRepSrv.ArrayOfString[] GetZRepStringsResult;
        
        public GetZRepStringsResponseBody() {
        }
        
        public GetZRepStringsResponseBody(PDCardSummChecker.ZRepSrv.ArrayOfString[] GetZRepStringsResult) {
            this.GetZRepStringsResult = GetZRepStringsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZRepStringsTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZRepStringsTest", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.GetZRepStringsTestRequestBody Body;
        
        public GetZRepStringsTestRequest() {
        }
        
        public GetZRepStringsTestRequest(PDCardSummChecker.ZRepSrv.GetZRepStringsTestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetZRepStringsTestRequestBody {
        
        public GetZRepStringsTestRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZRepStringsTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZRepStringsTestResponse", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.GetZRepStringsTestResponseBody Body;
        
        public GetZRepStringsTestResponse() {
        }
        
        public GetZRepStringsTestResponse(PDCardSummChecker.ZRepSrv.GetZRepStringsTestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class GetZRepStringsTestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PDCardSummChecker.ZRepSrv.ArrayOfString GetZRepStringsTestResult;
        
        public GetZRepStringsTestResponseBody() {
        }
        
        public GetZRepStringsTestResponseBody(PDCardSummChecker.ZRepSrv.ArrayOfString GetZRepStringsTestResult) {
            this.GetZRepStringsTestResult = GetZRepStringsTestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZRep3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZRep3", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.GetZRep3RequestBody Body;
        
        public GetZRep3Request() {
        }
        
        public GetZRep3Request(PDCardSummChecker.ZRepSrv.GetZRep3RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class GetZRep3RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime BusinessDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int DepNum;
        
        public GetZRep3RequestBody() {
        }
        
        public GetZRep3RequestBody(System.DateTime BusinessDate, int DepNum) {
            this.BusinessDate = BusinessDate;
            this.DepNum = DepNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZRep3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZRep3Response", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.GetZRep3ResponseBody Body;
        
        public GetZRep3Response() {
        }
        
        public GetZRep3Response(PDCardSummChecker.ZRepSrv.GetZRep3ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class GetZRep3ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PDiscountCard.ZRepSrv.TblZReports2[] GetZRep3Result;
        
        public GetZRep3ResponseBody() {
        }
        
        public GetZRep3ResponseBody(PDiscountCard.ZRepSrv.TblZReports2[] GetZRep3Result) {
            this.GetZRep3Result = GetZRep3Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZRep2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZRep2", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.GetZRep2RequestBody Body;
        
        public GetZRep2Request() {
        }
        
        public GetZRep2Request(PDCardSummChecker.ZRepSrv.GetZRep2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class GetZRep2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime BusinessDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int UnDepNum;
        
        public GetZRep2RequestBody() {
        }
        
        public GetZRep2RequestBody(System.DateTime BusinessDate, int UnDepNum) {
            this.BusinessDate = BusinessDate;
            this.UnDepNum = UnDepNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZRep2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZRep2Response", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.GetZRep2ResponseBody Body;
        
        public GetZRep2Response() {
        }
        
        public GetZRep2Response(PDCardSummChecker.ZRepSrv.GetZRep2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class GetZRep2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PDiscountCard.ZRepSrv.ZReportInfo[] GetZRep2Result;
        
        public GetZRep2ResponseBody() {
        }
        
        public GetZRep2ResponseBody(PDiscountCard.ZRepSrv.ZReportInfo[] GetZRep2Result) {
            this.GetZRep2Result = GetZRep2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetChecksByDofBandDepRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetChecksByDofBandDep", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.GetChecksByDofBandDepRequestBody Body;
        
        public GetChecksByDofBandDepRequest() {
        }
        
        public GetChecksByDofBandDepRequest(PDCardSummChecker.ZRepSrv.GetChecksByDofBandDepRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class GetChecksByDofBandDepRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime BD;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Dep;
        
        public GetChecksByDofBandDepRequestBody() {
        }
        
        public GetChecksByDofBandDepRequestBody(System.DateTime BD, int Dep) {
            this.BD = BD;
            this.Dep = Dep;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetChecksByDofBandDepResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetChecksByDofBandDepResponse", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.GetChecksByDofBandDepResponseBody Body;
        
        public GetChecksByDofBandDepResponse() {
        }
        
        public GetChecksByDofBandDepResponse(PDCardSummChecker.ZRepSrv.GetChecksByDofBandDepResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class GetChecksByDofBandDepResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PDCardSummChecker.ZRepSrv.XmlCheckRecive[] GetChecksByDofBandDepResult;
        
        public GetChecksByDofBandDepResponseBody() {
        }
        
        public GetChecksByDofBandDepResponseBody(PDCardSummChecker.ZRepSrv.XmlCheckRecive[] GetChecksByDofBandDepResult) {
            this.GetChecksByDofBandDepResult = GetChecksByDofBandDepResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDepsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllDeps", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.GetAllDepsRequestBody Body;
        
        public GetAllDepsRequest() {
        }
        
        public GetAllDepsRequest(PDCardSummChecker.ZRepSrv.GetAllDepsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllDepsRequestBody {
        
        public GetAllDepsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDepsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllDepsResponse", Namespace="http://Piskov.org/", Order=0)]
        public PDCardSummChecker.ZRepSrv.GetAllDepsResponseBody Body;
        
        public GetAllDepsResponse() {
        }
        
        public GetAllDepsResponse(PDCardSummChecker.ZRepSrv.GetAllDepsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Piskov.org/")]
    public partial class GetAllDepsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PDiscountCard.ZRepSrv.DimTable[] GetAllDepsResult;
        
        public GetAllDepsResponseBody() {
        }
        
        public GetAllDepsResponseBody(PDiscountCard.ZRepSrv.DimTable[] GetAllDepsResult) {
            this.GetAllDepsResult = GetAllDepsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : PDCardSummChecker.ZRepSrv.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<PDCardSummChecker.ZRepSrv.Service1Soap>, PDCardSummChecker.ZRepSrv.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PDCardSummChecker.ZRepSrv.GetZReportsResponse PDCardSummChecker.ZRepSrv.Service1Soap.GetZReports(PDCardSummChecker.ZRepSrv.GetZReportsRequest request) {
            return base.Channel.GetZReports(request);
        }
        
        public string GetZReports(System.DateTime BusinessDate, int DepNum, int TermNum) {
            PDCardSummChecker.ZRepSrv.GetZReportsRequest inValue = new PDCardSummChecker.ZRepSrv.GetZReportsRequest();
            inValue.Body = new PDCardSummChecker.ZRepSrv.GetZReportsRequestBody();
            inValue.Body.BusinessDate = BusinessDate;
            inValue.Body.DepNum = DepNum;
            inValue.Body.TermNum = TermNum;
            PDCardSummChecker.ZRepSrv.GetZReportsResponse retVal = ((PDCardSummChecker.ZRepSrv.Service1Soap)(this)).GetZReports(inValue);
            return retVal.Body.GetZReportsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PDCardSummChecker.ZRepSrv.GetKKmsSumFromStartLifeResponse PDCardSummChecker.ZRepSrv.Service1Soap.GetKKmsSumFromStartLife(PDCardSummChecker.ZRepSrv.GetKKmsSumFromStartLifeRequest request) {
            return base.Channel.GetKKmsSumFromStartLife(request);
        }
        
        public PDCardSummChecker.ZRepSrv.ArrayOfInt GetKKmsSumFromStartLife() {
            PDCardSummChecker.ZRepSrv.GetKKmsSumFromStartLifeRequest inValue = new PDCardSummChecker.ZRepSrv.GetKKmsSumFromStartLifeRequest();
            inValue.Body = new PDCardSummChecker.ZRepSrv.GetKKmsSumFromStartLifeRequestBody();
            PDCardSummChecker.ZRepSrv.GetKKmsSumFromStartLifeResponse retVal = ((PDCardSummChecker.ZRepSrv.Service1Soap)(this)).GetKKmsSumFromStartLife(inValue);
            return retVal.Body.GetKKmsSumFromStartLifeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PDCardSummChecker.ZRepSrv.TestResponse PDCardSummChecker.ZRepSrv.Service1Soap.Test(PDCardSummChecker.ZRepSrv.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public string Test() {
            PDCardSummChecker.ZRepSrv.TestRequest inValue = new PDCardSummChecker.ZRepSrv.TestRequest();
            inValue.Body = new PDCardSummChecker.ZRepSrv.TestRequestBody();
            PDCardSummChecker.ZRepSrv.TestResponse retVal = ((PDCardSummChecker.ZRepSrv.Service1Soap)(this)).Test(inValue);
            return retVal.Body.TestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PDCardSummChecker.ZRepSrv.AddErrorResponse PDCardSummChecker.ZRepSrv.Service1Soap.AddError(PDCardSummChecker.ZRepSrv.AddErrorRequest request) {
            return base.Channel.AddError(request);
        }
        
        public void AddError(string Message, int _DepNum, int Term) {
            PDCardSummChecker.ZRepSrv.AddErrorRequest inValue = new PDCardSummChecker.ZRepSrv.AddErrorRequest();
            inValue.Body = new PDCardSummChecker.ZRepSrv.AddErrorRequestBody();
            inValue.Body.Message = Message;
            inValue.Body._DepNum = _DepNum;
            inValue.Body.Term = Term;
            PDCardSummChecker.ZRepSrv.AddErrorResponse retVal = ((PDCardSummChecker.ZRepSrv.Service1Soap)(this)).AddError(inValue);
        }
        
        public void ConvertData(int UnDepNumber) {
            base.Channel.ConvertData(UnDepNumber);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PDCardSummChecker.ZRepSrv.AddHamsterCheckResponse PDCardSummChecker.ZRepSrv.Service1Soap.AddHamsterCheck(PDCardSummChecker.ZRepSrv.AddHamsterCheckRequest request) {
            return base.Channel.AddHamsterCheck(request);
        }
        
        public string AddHamsterCheck(string Data, int UnDepNumber, int DepNumber, string FileName) {
            PDCardSummChecker.ZRepSrv.AddHamsterCheckRequest inValue = new PDCardSummChecker.ZRepSrv.AddHamsterCheckRequest();
            inValue.Body = new PDCardSummChecker.ZRepSrv.AddHamsterCheckRequestBody();
            inValue.Body.Data = Data;
            inValue.Body.UnDepNumber = UnDepNumber;
            inValue.Body.DepNumber = DepNumber;
            inValue.Body.FileName = FileName;
            PDCardSummChecker.ZRepSrv.AddHamsterCheckResponse retVal = ((PDCardSummChecker.ZRepSrv.Service1Soap)(this)).AddHamsterCheck(inValue);
            return retVal.Body.AddHamsterCheckResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PDCardSummChecker.ZRepSrv.AddHamsterChecksResponse PDCardSummChecker.ZRepSrv.Service1Soap.AddHamsterChecks(PDCardSummChecker.ZRepSrv.AddHamsterChecksRequest request) {
            return base.Channel.AddHamsterChecks(request);
        }
        
        public string AddHamsterChecks(System.Xml.Linq.XElement Data, int UnDepNumber, int DepNumber, string FileName) {
            PDCardSummChecker.ZRepSrv.AddHamsterChecksRequest inValue = new PDCardSummChecker.ZRepSrv.AddHamsterChecksRequest();
            inValue.Body = new PDCardSummChecker.ZRepSrv.AddHamsterChecksRequestBody();
            inValue.Body.Data = Data;
            inValue.Body.UnDepNumber = UnDepNumber;
            inValue.Body.DepNumber = DepNumber;
            inValue.Body.FileName = FileName;
            PDCardSummChecker.ZRepSrv.AddHamsterChecksResponse retVal = ((PDCardSummChecker.ZRepSrv.Service1Soap)(this)).AddHamsterChecks(inValue);
            return retVal.Body.AddHamsterChecksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PDCardSummChecker.ZRepSrv.CopyLogFileResponse PDCardSummChecker.ZRepSrv.Service1Soap.CopyLogFile(PDCardSummChecker.ZRepSrv.CopyLogFileRequest request) {
            return base.Channel.CopyLogFile(request);
        }
        
        public PDiscountCard.ZRepSrv.CopyCheckFileResult CopyLogFile(byte[] data, long OriginalDataLenght, string FName, int UnDepNumber, int DepNumber, int FType) {
            PDCardSummChecker.ZRepSrv.CopyLogFileRequest inValue = new PDCardSummChecker.ZRepSrv.CopyLogFileRequest();
            inValue.Body = new PDCardSummChecker.ZRepSrv.CopyLogFileRequestBody();
            inValue.Body.data = data;
            inValue.Body.OriginalDataLenght = OriginalDataLenght;
            inValue.Body.FName = FName;
            inValue.Body.UnDepNumber = UnDepNumber;
            inValue.Body.DepNumber = DepNumber;
            inValue.Body.FType = FType;
            PDCardSummChecker.ZRepSrv.CopyLogFileResponse retVal = ((PDCardSummChecker.ZRepSrv.Service1Soap)(this)).CopyLogFile(inValue);
            return retVal.Body.CopyLogFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PDCardSummChecker.ZRepSrv.CopyCheckFileResponse PDCardSummChecker.ZRepSrv.Service1Soap.CopyCheckFile(PDCardSummChecker.ZRepSrv.CopyCheckFileRequest request) {
            return base.Channel.CopyCheckFile(request);
        }
        
        public PDiscountCard.ZRepSrv.CopyCheckFileResult CopyCheckFile(byte[] data, long OriginalDataLenght, string FName, int UnDepNumber, int DepNumber) {
            PDCardSummChecker.ZRepSrv.CopyCheckFileRequest inValue = new PDCardSummChecker.ZRepSrv.CopyCheckFileRequest();
            inValue.Body = new PDCardSummChecker.ZRepSrv.CopyCheckFileRequestBody();
            inValue.Body.data = data;
            inValue.Body.OriginalDataLenght = OriginalDataLenght;
            inValue.Body.FName = FName;
            inValue.Body.UnDepNumber = UnDepNumber;
            inValue.Body.DepNumber = DepNumber;
            PDCardSummChecker.ZRepSrv.CopyCheckFileResponse retVal = ((PDCardSummChecker.ZRepSrv.Service1Soap)(this)).CopyCheckFile(inValue);
            return retVal.Body.CopyCheckFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PDCardSummChecker.ZRepSrv.AddPaymentCardInfoResponse PDCardSummChecker.ZRepSrv.Service1Soap.AddPaymentCardInfo(PDCardSummChecker.ZRepSrv.AddPaymentCardInfoRequest request) {
            return base.Channel.AddPaymentCardInfo(request);
        }
        
        public bool AddPaymentCardInfo(PDiscountCard.ZRepSrv.PaymentCard mPaymentCardInfo) {
            PDCardSummChecker.ZRepSrv.AddPaymentCardInfoRequest inValue = new PDCardSummChecker.ZRepSrv.AddPaymentCardInfoRequest();
            inValue.Body = new PDCardSummChecker.ZRepSrv.AddPaymentCardInfoRequestBody();
            inValue.Body.mPaymentCardInfo = mPaymentCardInfo;
            PDCardSummChecker.ZRepSrv.AddPaymentCardInfoResponse retVal = ((PDCardSummChecker.ZRepSrv.Service1Soap)(this)).AddPaymentCardInfo(inValue);
            return retVal.Body.AddPaymentCardInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PDCardSummChecker.ZRepSrv.GetPaymentCardInfoReportResponse PDCardSummChecker.ZRepSrv.Service1Soap.GetPaymentCardInfoReport(PDCardSummChecker.ZRepSrv.GetPaymentCardInfoReportRequest request) {
            return base.Channel.GetPaymentCardInfoReport(request);
        }
        
        public PDiscountCard.ZRepSrv.PaymentCard[] GetPaymentCardInfoReport(int UndepNum, System.DateTime Bdate) {
            PDCardSummChecker.ZRepSrv.GetPaymentCardInfoReportRequest inValue = new PDCardSummChecker.ZRepSrv.GetPaymentCardInfoReportRequest();
            inValue.Body = new PDCardSummChecker.ZRepSrv.GetPaymentCardInfoReportRequestBody();
            inValue.Body.UndepNum = UndepNum;
            inValue.Body.Bdate = Bdate;
            PDCardSummChecker.ZRepSrv.GetPaymentCardInfoReportResponse retVal = ((PDCardSummChecker.ZRepSrv.Service1Soap)(this)).GetPaymentCardInfoReport(inValue);
            return retVal.Body.GetPaymentCardInfoReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PDCardSummChecker.ZRepSrv.AddZRep2Response PDCardSummChecker.ZRepSrv.Service1Soap.AddZRep2(PDCardSummChecker.ZRepSrv.AddZRep2Request request) {
            return base.Channel.AddZRep2(request);
        }
        
        public string AddZRep2(PDiscountCard.ZRepSrv.TblZReports2 Rep) {
            PDCardSummChecker.ZRepSrv.AddZRep2Request inValue = new PDCardSummChecker.ZRepSrv.AddZRep2Request();
            inValue.Body = new PDCardSummChecker.ZRepSrv.AddZRep2RequestBody();
            inValue.Body.Rep = Rep;
            PDCardSummChecker.ZRepSrv.AddZRep2Response retVal = ((PDCardSummChecker.ZRepSrv.Service1Soap)(this)).AddZRep2(inValue);
            return retVal.Body.AddZRep2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PDCardSummChecker.ZRepSrv.AddZRepResponse PDCardSummChecker.ZRepSrv.Service1Soap.AddZRep(PDCardSummChecker.ZRepSrv.AddZRepRequest request) {
            return base.Channel.AddZRep(request);
        }
        
        public string AddZRep(PDiscountCard.ZRepSrv.ZReportInfo ZInfo) {
            PDCardSummChecker.ZRepSrv.AddZRepRequest inValue = new PDCardSummChecker.ZRepSrv.AddZRepRequest();
            inValue.Body = new PDCardSummChecker.ZRepSrv.AddZRepRequestBody();
            inValue.Body.ZInfo = ZInfo;
            PDCardSummChecker.ZRepSrv.AddZRepResponse retVal = ((PDCardSummChecker.ZRepSrv.Service1Soap)(this)).AddZRep(inValue);
            return retVal.Body.AddZRepResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PDCardSummChecker.ZRepSrv.GetZRepResponse PDCardSummChecker.ZRepSrv.Service1Soap.GetZRep(PDCardSummChecker.ZRepSrv.GetZRepRequest request) {
            return base.Channel.GetZRep(request);
        }
        
        public PDiscountCard.ZRepSrv.ZReportInfo GetZRep(System.DateTime BusinessDate, int UnDepNum) {
            PDCardSummChecker.ZRepSrv.GetZRepRequest inValue = new PDCardSummChecker.ZRepSrv.GetZRepRequest();
            inValue.Body = new PDCardSummChecker.ZRepSrv.GetZRepRequestBody();
            inValue.Body.BusinessDate = BusinessDate;
            inValue.Body.UnDepNum = UnDepNum;
            PDCardSummChecker.ZRepSrv.GetZRepResponse retVal = ((PDCardSummChecker.ZRepSrv.Service1Soap)(this)).GetZRep(inValue);
            return retVal.Body.GetZRepResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PDCardSummChecker.ZRepSrv.GetCheckCountFromEklzResponse PDCardSummChecker.ZRepSrv.Service1Soap.GetCheckCountFromEklz(PDCardSummChecker.ZRepSrv.GetCheckCountFromEklzRequest request) {
            return base.Channel.GetCheckCountFromEklz(request);
        }
        
        public int GetCheckCountFromEklz(string kkmnum, int repnum2) {
            PDCardSummChecker.ZRepSrv.GetCheckCountFromEklzRequest inValue = new PDCardSummChecker.ZRepSrv.GetCheckCountFromEklzRequest();
            inValue.Body = new PDCardSummChecker.ZRepSrv.GetCheckCountFromEklzRequestBody();
            inValue.Body.kkmnum = kkmnum;
            inValue.Body.repnum2 = repnum2;
            PDCardSummChecker.ZRepSrv.GetCheckCountFromEklzResponse retVal = ((PDCardSummChecker.ZRepSrv.Service1Soap)(this)).GetCheckCountFromEklz(inValue);
            return retVal.Body.GetCheckCountFromEklzResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PDCardSummChecker.ZRepSrv.GetZRepStringsResponse PDCardSummChecker.ZRepSrv.Service1Soap.GetZRepStrings(PDCardSummChecker.ZRepSrv.GetZRepStringsRequest request) {
            return base.Channel.GetZRepStrings(request);
        }
        
        public PDCardSummChecker.ZRepSrv.ArrayOfString[] GetZRepStrings(System.DateTime BusinessDate, int DepNum, int Term) {
            PDCardSummChecker.ZRepSrv.GetZRepStringsRequest inValue = new PDCardSummChecker.ZRepSrv.GetZRepStringsRequest();
            inValue.Body = new PDCardSummChecker.ZRepSrv.GetZRepStringsRequestBody();
            inValue.Body.BusinessDate = BusinessDate;
            inValue.Body.DepNum = DepNum;
            inValue.Body.Term = Term;
            PDCardSummChecker.ZRepSrv.GetZRepStringsResponse retVal = ((PDCardSummChecker.ZRepSrv.Service1Soap)(this)).GetZRepStrings(inValue);
            return retVal.Body.GetZRepStringsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PDCardSummChecker.ZRepSrv.GetZRepStringsTestResponse PDCardSummChecker.ZRepSrv.Service1Soap.GetZRepStringsTest(PDCardSummChecker.ZRepSrv.GetZRepStringsTestRequest request) {
            return base.Channel.GetZRepStringsTest(request);
        }
        
        public PDCardSummChecker.ZRepSrv.ArrayOfString GetZRepStringsTest() {
            PDCardSummChecker.ZRepSrv.GetZRepStringsTestRequest inValue = new PDCardSummChecker.ZRepSrv.GetZRepStringsTestRequest();
            inValue.Body = new PDCardSummChecker.ZRepSrv.GetZRepStringsTestRequestBody();
            PDCardSummChecker.ZRepSrv.GetZRepStringsTestResponse retVal = ((PDCardSummChecker.ZRepSrv.Service1Soap)(this)).GetZRepStringsTest(inValue);
            return retVal.Body.GetZRepStringsTestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PDCardSummChecker.ZRepSrv.GetZRep3Response PDCardSummChecker.ZRepSrv.Service1Soap.GetZRep3(PDCardSummChecker.ZRepSrv.GetZRep3Request request) {
            return base.Channel.GetZRep3(request);
        }
        
        public PDiscountCard.ZRepSrv.TblZReports2[] GetZRep3(System.DateTime BusinessDate, int DepNum) {
            PDCardSummChecker.ZRepSrv.GetZRep3Request inValue = new PDCardSummChecker.ZRepSrv.GetZRep3Request();
            inValue.Body = new PDCardSummChecker.ZRepSrv.GetZRep3RequestBody();
            inValue.Body.BusinessDate = BusinessDate;
            inValue.Body.DepNum = DepNum;
            PDCardSummChecker.ZRepSrv.GetZRep3Response retVal = ((PDCardSummChecker.ZRepSrv.Service1Soap)(this)).GetZRep3(inValue);
            return retVal.Body.GetZRep3Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PDCardSummChecker.ZRepSrv.GetZRep2Response PDCardSummChecker.ZRepSrv.Service1Soap.GetZRep2(PDCardSummChecker.ZRepSrv.GetZRep2Request request) {
            return base.Channel.GetZRep2(request);
        }
        
        public PDiscountCard.ZRepSrv.ZReportInfo[] GetZRep2(System.DateTime BusinessDate, int UnDepNum) {
            PDCardSummChecker.ZRepSrv.GetZRep2Request inValue = new PDCardSummChecker.ZRepSrv.GetZRep2Request();
            inValue.Body = new PDCardSummChecker.ZRepSrv.GetZRep2RequestBody();
            inValue.Body.BusinessDate = BusinessDate;
            inValue.Body.UnDepNum = UnDepNum;
            PDCardSummChecker.ZRepSrv.GetZRep2Response retVal = ((PDCardSummChecker.ZRepSrv.Service1Soap)(this)).GetZRep2(inValue);
            return retVal.Body.GetZRep2Result;
        }
        
        public int DepIsWhite(int _DepNum) {
            return base.Channel.DepIsWhite(_DepNum);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PDCardSummChecker.ZRepSrv.GetChecksByDofBandDepResponse PDCardSummChecker.ZRepSrv.Service1Soap.GetChecksByDofBandDep(PDCardSummChecker.ZRepSrv.GetChecksByDofBandDepRequest request) {
            return base.Channel.GetChecksByDofBandDep(request);
        }
        
        public PDCardSummChecker.ZRepSrv.XmlCheckRecive[] GetChecksByDofBandDep(System.DateTime BD, int Dep) {
            PDCardSummChecker.ZRepSrv.GetChecksByDofBandDepRequest inValue = new PDCardSummChecker.ZRepSrv.GetChecksByDofBandDepRequest();
            inValue.Body = new PDCardSummChecker.ZRepSrv.GetChecksByDofBandDepRequestBody();
            inValue.Body.BD = BD;
            inValue.Body.Dep = Dep;
            PDCardSummChecker.ZRepSrv.GetChecksByDofBandDepResponse retVal = ((PDCardSummChecker.ZRepSrv.Service1Soap)(this)).GetChecksByDofBandDep(inValue);
            return retVal.Body.GetChecksByDofBandDepResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PDCardSummChecker.ZRepSrv.GetAllDepsResponse PDCardSummChecker.ZRepSrv.Service1Soap.GetAllDeps(PDCardSummChecker.ZRepSrv.GetAllDepsRequest request) {
            return base.Channel.GetAllDeps(request);
        }
        
        public PDiscountCard.ZRepSrv.DimTable[] GetAllDeps() {
            PDCardSummChecker.ZRepSrv.GetAllDepsRequest inValue = new PDCardSummChecker.ZRepSrv.GetAllDepsRequest();
            inValue.Body = new PDCardSummChecker.ZRepSrv.GetAllDepsRequestBody();
            PDCardSummChecker.ZRepSrv.GetAllDepsResponse retVal = ((PDCardSummChecker.ZRepSrv.Service1Soap)(this)).GetAllDeps(inValue);
            return retVal.Body.GetAllDepsResult;
        }
    }
}
