//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDTest.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddCheckRequest", Namespace="http://schemas.datacontract.org/2004/07/FRS")]
    [System.SerializableAttribute()]
    public partial class AddCheckRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PDTest.ServiceReference1.FiskalCheck CheckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PDTest.ServiceReference1.FiskalCheck Check {
            get {
                return this.CheckField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckField, value) != true)) {
                    this.CheckField = value;
                    this.RaisePropertyChanged("Check");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FiskalCheck", Namespace="http://schemas.datacontract.org/2004/07/FRS")]
    [System.SerializableAttribute()]
    public partial class FiskalCheck : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ClosedSucseesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PDTest.ServiceReference1.FiskalDish[] DishesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExtNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtNumDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PDTest.ServiceReference1.FCheckOutData FROutDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PDTest.ServiceReference1.FiskalPayment[] PaymentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ReturnSaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] StringsForPrintField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ClosedSucsees {
            get {
                return this.ClosedSucseesField;
            }
            set {
                if ((this.ClosedSucseesField.Equals(value) != true)) {
                    this.ClosedSucseesField = value;
                    this.RaisePropertyChanged("ClosedSucsees");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PDTest.ServiceReference1.FiskalDish[] Dishes {
            get {
                return this.DishesField;
            }
            set {
                if ((object.ReferenceEquals(this.DishesField, value) != true)) {
                    this.DishesField = value;
                    this.RaisePropertyChanged("Dishes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExtNum {
            get {
                return this.ExtNumField;
            }
            set {
                if ((this.ExtNumField.Equals(value) != true)) {
                    this.ExtNumField = value;
                    this.RaisePropertyChanged("ExtNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtNumData {
            get {
                return this.ExtNumDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtNumDataField, value) != true)) {
                    this.ExtNumDataField = value;
                    this.RaisePropertyChanged("ExtNumData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PDTest.ServiceReference1.FCheckOutData FROutData {
            get {
                return this.FROutDataField;
            }
            set {
                if ((object.ReferenceEquals(this.FROutDataField, value) != true)) {
                    this.FROutDataField = value;
                    this.RaisePropertyChanged("FROutData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PDTest.ServiceReference1.FiskalPayment[] Payments {
            get {
                return this.PaymentsField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentsField, value) != true)) {
                    this.PaymentsField = value;
                    this.RaisePropertyChanged("Payments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReturnSale {
            get {
                return this.ReturnSaleField;
            }
            set {
                if ((this.ReturnSaleField.Equals(value) != true)) {
                    this.ReturnSaleField = value;
                    this.RaisePropertyChanged("ReturnSale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] StringsForPrint {
            get {
                return this.StringsForPrintField;
            }
            set {
                if ((object.ReferenceEquals(this.StringsForPrintField, value) != true)) {
                    this.StringsForPrintField = value;
                    this.RaisePropertyChanged("StringsForPrint");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FCheckOutData", Namespace="http://schemas.datacontract.org/2004/07/FRS")]
    [System.SerializableAttribute()]
    public partial class FCheckOutData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ChangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QRAsStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SmallNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SummField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SysDtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int bigNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Change {
            get {
                return this.ChangeField;
            }
            set {
                if ((this.ChangeField.Equals(value) != true)) {
                    this.ChangeField = value;
                    this.RaisePropertyChanged("Change");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FD {
            get {
                return this.FDField;
            }
            set {
                if ((this.FDField.Equals(value) != true)) {
                    this.FDField = value;
                    this.RaisePropertyChanged("FD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FP {
            get {
                return this.FPField;
            }
            set {
                if ((object.ReferenceEquals(this.FPField, value) != true)) {
                    this.FPField = value;
                    this.RaisePropertyChanged("FP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QRAsStr {
            get {
                return this.QRAsStrField;
            }
            set {
                if ((object.ReferenceEquals(this.QRAsStrField, value) != true)) {
                    this.QRAsStrField = value;
                    this.RaisePropertyChanged("QRAsStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SmallNum {
            get {
                return this.SmallNumField;
            }
            set {
                if ((this.SmallNumField.Equals(value) != true)) {
                    this.SmallNumField = value;
                    this.RaisePropertyChanged("SmallNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Summ {
            get {
                return this.SummField;
            }
            set {
                if ((this.SummField.Equals(value) != true)) {
                    this.SummField = value;
                    this.RaisePropertyChanged("Summ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SysDt {
            get {
                return this.SysDtField;
            }
            set {
                if ((this.SysDtField.Equals(value) != true)) {
                    this.SysDtField = value;
                    this.RaisePropertyChanged("SysDt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int bigNum {
            get {
                return this.bigNumField;
            }
            set {
                if ((this.bigNumField.Equals(value) != true)) {
                    this.bigNumField = value;
                    this.RaisePropertyChanged("bigNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FiskalDish", Namespace="http://schemas.datacontract.org/2004/07/FRS")]
    [System.SerializableAttribute()]
    public partial class FiskalDish : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FiskalPayment", Namespace="http://schemas.datacontract.org/2004/07/FRS")]
    [System.SerializableAttribute()]
    public partial class FiskalPayment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SummField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Summ {
            get {
                return this.SummField;
            }
            set {
                if ((this.SummField.Equals(value) != true)) {
                    this.SummField = value;
                    this.RaisePropertyChanged("Summ");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddCheckResponce", Namespace="http://schemas.datacontract.org/2004/07/FRS")]
    [System.SerializableAttribute()]
    public partial class AddCheckResponce : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PDTest.ServiceReference1.FRAttributes AttrsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PDTest.ServiceReference1.FiskalCheck CheckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PDTest.ServiceReference1.FRAttributes Attrs {
            get {
                return this.AttrsField;
            }
            set {
                if ((object.ReferenceEquals(this.AttrsField, value) != true)) {
                    this.AttrsField = value;
                    this.RaisePropertyChanged("Attrs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PDTest.ServiceReference1.FiskalCheck Check {
            get {
                return this.CheckField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckField, value) != true)) {
                    this.CheckField = value;
                    this.RaisePropertyChanged("Check");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FRAttributes", Namespace="http://schemas.datacontract.org/2004/07/FRS")]
    [System.SerializableAttribute()]
    public partial class FRAttributes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FNNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string INNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] KlisheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, string> PaymentNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SmenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZNField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FNNumber {
            get {
                return this.FNNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.FNNumberField, value) != true)) {
                    this.FNNumberField = value;
                    this.RaisePropertyChanged("FNNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string INN {
            get {
                return this.INNField;
            }
            set {
                if ((object.ReferenceEquals(this.INNField, value) != true)) {
                    this.INNField = value;
                    this.RaisePropertyChanged("INN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Klishe {
            get {
                return this.KlisheField;
            }
            set {
                if ((object.ReferenceEquals(this.KlisheField, value) != true)) {
                    this.KlisheField = value;
                    this.RaisePropertyChanged("Klishe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, string> PaymentNames {
            get {
                return this.PaymentNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentNamesField, value) != true)) {
                    this.PaymentNamesField = value;
                    this.RaisePropertyChanged("PaymentNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RN {
            get {
                return this.RNField;
            }
            set {
                if ((object.ReferenceEquals(this.RNField, value) != true)) {
                    this.RNField = value;
                    this.RaisePropertyChanged("RN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Smena {
            get {
                return this.SmenaField;
            }
            set {
                if ((this.SmenaField.Equals(value) != true)) {
                    this.SmenaField = value;
                    this.RaisePropertyChanged("Smena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZN {
            get {
                return this.ZNField;
            }
            set {
                if ((object.ReferenceEquals(this.ZNField, value) != true)) {
                    this.ZNField = value;
                    this.RaisePropertyChanged("ZN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://FRS.Srv", ConfigurationName="ServiceReference1.IRemoteData")]
    public interface IRemoteData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FRS.Srv/IRemoteData/AddCheck", ReplyAction="http://FRS.Srv/IRemoteData/AddCheckResponse")]
        PDTest.ServiceReference1.AddCheckResponce AddCheck(PDTest.ServiceReference1.AddCheckRequest Request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRemoteDataChannel : PDTest.ServiceReference1.IRemoteData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RemoteDataClient : System.ServiceModel.ClientBase<PDTest.ServiceReference1.IRemoteData>, PDTest.ServiceReference1.IRemoteData {
        
        public RemoteDataClient() {
        }
        
        public RemoteDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RemoteDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemoteDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemoteDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PDTest.ServiceReference1.AddCheckResponce AddCheck(PDTest.ServiceReference1.AddCheckRequest Request) {
            return base.Channel.AddCheck(Request);
        }
    }
}
