//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PDiscountCard.StopListService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://coffeemania.ru/VPiskov")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback MenuModifEnabledOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendGloryLogOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGloryLogOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEventOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlohaEventSendOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlohaEventSend2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetResonTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoteEventSendOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCurentResonsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddStopListReasonsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetDishListOperationCompleted;
        
        private System.Threading.SendOrPostCallback SeтMnuToServerOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetMnuToServerOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::PDiscountCard.Properties.Settings.Default.PDiscountCard_sadkudr1_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event MenuModifEnabledCompletedEventHandler MenuModifEnabledCompleted;
        
        /// <remarks/>
        public event SendGloryLogCompletedEventHandler SendGloryLogCompleted;
        
        /// <remarks/>
        public event GetGloryLogCompletedEventHandler GetGloryLogCompleted;
        
        /// <remarks/>
        public event GetEventCompletedEventHandler GetEventCompleted;
        
        /// <remarks/>
        public event AlohaEventSendCompletedEventHandler AlohaEventSendCompleted;
        
        /// <remarks/>
        public event AlohaEventSend2CompletedEventHandler AlohaEventSend2Completed;
        
        /// <remarks/>
        public event GetResonTypesCompletedEventHandler GetResonTypesCompleted;
        
        /// <remarks/>
        public event RemoteEventSendCompletedEventHandler RemoteEventSendCompleted;
        
        /// <remarks/>
        public event GetCurentResonsCompletedEventHandler GetCurentResonsCompleted;
        
        /// <remarks/>
        public event AddStopListReasonsCompletedEventHandler AddStopListReasonsCompleted;
        
        /// <remarks/>
        public event SetDishListCompletedEventHandler SetDishListCompleted;
        
        /// <remarks/>
        public event SeтMnuToServerCompletedEventHandler SeтMnuToServerCompleted;
        
        /// <remarks/>
        public event SetMnuToServerCompletedEventHandler SetMnuToServerCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://coffeemania.ru/VPiskov/MenuModifEnabled", RequestNamespace="http://coffeemania.ru/VPiskov", ResponseNamespace="http://coffeemania.ru/VPiskov", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool MenuModifEnabled(int DepId) {
            object[] results = this.Invoke("MenuModifEnabled", new object[] {
                        DepId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void MenuModifEnabledAsync(int DepId) {
            this.MenuModifEnabledAsync(DepId, null);
        }
        
        /// <remarks/>
        public void MenuModifEnabledAsync(int DepId, object userState) {
            if ((this.MenuModifEnabledOperationCompleted == null)) {
                this.MenuModifEnabledOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMenuModifEnabledOperationCompleted);
            }
            this.InvokeAsync("MenuModifEnabled", new object[] {
                        DepId}, this.MenuModifEnabledOperationCompleted, userState);
        }
        
        private void OnMenuModifEnabledOperationCompleted(object arg) {
            if ((this.MenuModifEnabledCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MenuModifEnabledCompleted(this, new MenuModifEnabledCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://coffeemania.ru/VPiskov/SendGloryLog", RequestNamespace="http://coffeemania.ru/VPiskov", ResponseNamespace="http://coffeemania.ru/VPiskov", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendGloryLog(int Dep, int Term, string Message) {
            this.Invoke("SendGloryLog", new object[] {
                        Dep,
                        Term,
                        Message});
        }
        
        /// <remarks/>
        public void SendGloryLogAsync(int Dep, int Term, string Message) {
            this.SendGloryLogAsync(Dep, Term, Message, null);
        }
        
        /// <remarks/>
        public void SendGloryLogAsync(int Dep, int Term, string Message, object userState) {
            if ((this.SendGloryLogOperationCompleted == null)) {
                this.SendGloryLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendGloryLogOperationCompleted);
            }
            this.InvokeAsync("SendGloryLog", new object[] {
                        Dep,
                        Term,
                        Message}, this.SendGloryLogOperationCompleted, userState);
        }
        
        private void OnSendGloryLogOperationCompleted(object arg) {
            if ((this.SendGloryLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendGloryLogCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://coffeemania.ru/VPiskov/GetGloryLog", RequestNamespace="http://coffeemania.ru/VPiskov", ResponseNamespace="http://coffeemania.ru/VPiskov", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetGloryLog(int Dep, int Term, System.DateTime StartDt, System.DateTime StopDt) {
            object[] results = this.Invoke("GetGloryLog", new object[] {
                        Dep,
                        Term,
                        StartDt,
                        StopDt});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetGloryLogAsync(int Dep, int Term, System.DateTime StartDt, System.DateTime StopDt) {
            this.GetGloryLogAsync(Dep, Term, StartDt, StopDt, null);
        }
        
        /// <remarks/>
        public void GetGloryLogAsync(int Dep, int Term, System.DateTime StartDt, System.DateTime StopDt, object userState) {
            if ((this.GetGloryLogOperationCompleted == null)) {
                this.GetGloryLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGloryLogOperationCompleted);
            }
            this.InvokeAsync("GetGloryLog", new object[] {
                        Dep,
                        Term,
                        StartDt,
                        StopDt}, this.GetGloryLogOperationCompleted, userState);
        }
        
        private void OnGetGloryLogOperationCompleted(object arg) {
            if ((this.GetGloryLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGloryLogCompleted(this, new GetGloryLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://coffeemania.ru/VPiskov/GetEvent", RequestNamespace="http://coffeemania.ru/VPiskov", ResponseNamespace="http://coffeemania.ru/VPiskov", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetEvent(int DepNum, long[] DishIds) {
            this.Invoke("GetEvent", new object[] {
                        DepNum,
                        DishIds});
        }
        
        /// <remarks/>
        public void GetEventAsync(int DepNum, long[] DishIds) {
            this.GetEventAsync(DepNum, DishIds, null);
        }
        
        /// <remarks/>
        public void GetEventAsync(int DepNum, long[] DishIds, object userState) {
            if ((this.GetEventOperationCompleted == null)) {
                this.GetEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEventOperationCompleted);
            }
            this.InvokeAsync("GetEvent", new object[] {
                        DepNum,
                        DishIds}, this.GetEventOperationCompleted, userState);
        }
        
        private void OnGetEventOperationCompleted(object arg) {
            if ((this.GetEventCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEventCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://coffeemania.ru/VPiskov/AlohaEventSend", RequestNamespace="http://coffeemania.ru/VPiskov", ResponseNamespace="http://coffeemania.ru/VPiskov", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlohaEventSend(int DepNum, int CassaNum, string _MashName, AlohaEventType EventType, int Code, int CodeDoljn, string Name) {
            this.Invoke("AlohaEventSend", new object[] {
                        DepNum,
                        CassaNum,
                        _MashName,
                        EventType,
                        Code,
                        CodeDoljn,
                        Name});
        }
        
        /// <remarks/>
        public void AlohaEventSendAsync(int DepNum, int CassaNum, string _MashName, AlohaEventType EventType, int Code, int CodeDoljn, string Name) {
            this.AlohaEventSendAsync(DepNum, CassaNum, _MashName, EventType, Code, CodeDoljn, Name, null);
        }
        
        /// <remarks/>
        public void AlohaEventSendAsync(int DepNum, int CassaNum, string _MashName, AlohaEventType EventType, int Code, int CodeDoljn, string Name, object userState) {
            if ((this.AlohaEventSendOperationCompleted == null)) {
                this.AlohaEventSendOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlohaEventSendOperationCompleted);
            }
            this.InvokeAsync("AlohaEventSend", new object[] {
                        DepNum,
                        CassaNum,
                        _MashName,
                        EventType,
                        Code,
                        CodeDoljn,
                        Name}, this.AlohaEventSendOperationCompleted, userState);
        }
        
        private void OnAlohaEventSendOperationCompleted(object arg) {
            if ((this.AlohaEventSendCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlohaEventSendCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://coffeemania.ru/VPiskov/AlohaEventSend2", RequestNamespace="http://coffeemania.ru/VPiskov", ResponseNamespace="http://coffeemania.ru/VPiskov", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlohaEventSend2(int DepNum, int CassaNum, string _MashName, AlohaEventType EventType, int Code, int CodeDoljn, string Name, int ToEmployeeId, int TableId, int CheckId) {
            this.Invoke("AlohaEventSend2", new object[] {
                        DepNum,
                        CassaNum,
                        _MashName,
                        EventType,
                        Code,
                        CodeDoljn,
                        Name,
                        ToEmployeeId,
                        TableId,
                        CheckId});
        }
        
        /// <remarks/>
        public void AlohaEventSend2Async(int DepNum, int CassaNum, string _MashName, AlohaEventType EventType, int Code, int CodeDoljn, string Name, int ToEmployeeId, int TableId, int CheckId) {
            this.AlohaEventSend2Async(DepNum, CassaNum, _MashName, EventType, Code, CodeDoljn, Name, ToEmployeeId, TableId, CheckId, null);
        }
        
        /// <remarks/>
        public void AlohaEventSend2Async(int DepNum, int CassaNum, string _MashName, AlohaEventType EventType, int Code, int CodeDoljn, string Name, int ToEmployeeId, int TableId, int CheckId, object userState) {
            if ((this.AlohaEventSend2OperationCompleted == null)) {
                this.AlohaEventSend2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlohaEventSend2OperationCompleted);
            }
            this.InvokeAsync("AlohaEventSend2", new object[] {
                        DepNum,
                        CassaNum,
                        _MashName,
                        EventType,
                        Code,
                        CodeDoljn,
                        Name,
                        ToEmployeeId,
                        TableId,
                        CheckId}, this.AlohaEventSend2OperationCompleted, userState);
        }
        
        private void OnAlohaEventSend2OperationCompleted(object arg) {
            if ((this.AlohaEventSend2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlohaEventSend2Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://coffeemania.ru/VPiskov/GetResonTypes", RequestNamespace="http://coffeemania.ru/VPiskov", ResponseNamespace="http://coffeemania.ru/VPiskov", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public StopListReasonT[] GetResonTypes() {
            object[] results = this.Invoke("GetResonTypes", new object[0]);
            return ((StopListReasonT[])(results[0]));
        }
        
        /// <remarks/>
        public void GetResonTypesAsync() {
            this.GetResonTypesAsync(null);
        }
        
        /// <remarks/>
        public void GetResonTypesAsync(object userState) {
            if ((this.GetResonTypesOperationCompleted == null)) {
                this.GetResonTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetResonTypesOperationCompleted);
            }
            this.InvokeAsync("GetResonTypes", new object[0], this.GetResonTypesOperationCompleted, userState);
        }
        
        private void OnGetResonTypesOperationCompleted(object arg) {
            if ((this.GetResonTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetResonTypesCompleted(this, new GetResonTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://coffeemania.ru/VPiskov/RemoteEventSend", RequestNamespace="http://coffeemania.ru/VPiskov", ResponseNamespace="http://coffeemania.ru/VPiskov", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoteEventSend(int DepNum, int CassaNum, string _MashName, RemoteEventType EventType, string Message) {
            this.Invoke("RemoteEventSend", new object[] {
                        DepNum,
                        CassaNum,
                        _MashName,
                        EventType,
                        Message});
        }
        
        /// <remarks/>
        public void RemoteEventSendAsync(int DepNum, int CassaNum, string _MashName, RemoteEventType EventType, string Message) {
            this.RemoteEventSendAsync(DepNum, CassaNum, _MashName, EventType, Message, null);
        }
        
        /// <remarks/>
        public void RemoteEventSendAsync(int DepNum, int CassaNum, string _MashName, RemoteEventType EventType, string Message, object userState) {
            if ((this.RemoteEventSendOperationCompleted == null)) {
                this.RemoteEventSendOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoteEventSendOperationCompleted);
            }
            this.InvokeAsync("RemoteEventSend", new object[] {
                        DepNum,
                        CassaNum,
                        _MashName,
                        EventType,
                        Message}, this.RemoteEventSendOperationCompleted, userState);
        }
        
        private void OnRemoteEventSendOperationCompleted(object arg) {
            if ((this.RemoteEventSendCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoteEventSendCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://coffeemania.ru/VPiskov/GetCurentResons", RequestNamespace="http://coffeemania.ru/VPiskov", ResponseNamespace="http://coffeemania.ru/VPiskov", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StopListReasonEvent[] GetCurentResons(int DepNum, out string Error) {
            object[] results = this.Invoke("GetCurentResons", new object[] {
                        DepNum});
            Error = ((string)(results[1]));
            return ((StopListReasonEvent[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCurentResonsAsync(int DepNum) {
            this.GetCurentResonsAsync(DepNum, null);
        }
        
        /// <remarks/>
        public void GetCurentResonsAsync(int DepNum, object userState) {
            if ((this.GetCurentResonsOperationCompleted == null)) {
                this.GetCurentResonsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCurentResonsOperationCompleted);
            }
            this.InvokeAsync("GetCurentResons", new object[] {
                        DepNum}, this.GetCurentResonsOperationCompleted, userState);
        }
        
        private void OnGetCurentResonsOperationCompleted(object arg) {
            if ((this.GetCurentResonsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCurentResonsCompleted(this, new GetCurentResonsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://coffeemania.ru/VPiskov/AddStopListReasons", RequestNamespace="http://coffeemania.ru/VPiskov", ResponseNamespace="http://coffeemania.ru/VPiskov", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddStopListReasons(StopListReasonEvent[] Res, out string ErrorMsg) {
            object[] results = this.Invoke("AddStopListReasons", new object[] {
                        Res});
            ErrorMsg = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddStopListReasonsAsync(StopListReasonEvent[] Res) {
            this.AddStopListReasonsAsync(Res, null);
        }
        
        /// <remarks/>
        public void AddStopListReasonsAsync(StopListReasonEvent[] Res, object userState) {
            if ((this.AddStopListReasonsOperationCompleted == null)) {
                this.AddStopListReasonsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddStopListReasonsOperationCompleted);
            }
            this.InvokeAsync("AddStopListReasons", new object[] {
                        Res}, this.AddStopListReasonsOperationCompleted, userState);
        }
        
        private void OnAddStopListReasonsOperationCompleted(object arg) {
            if ((this.AddStopListReasonsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddStopListReasonsCompleted(this, new AddStopListReasonsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://coffeemania.ru/VPiskov/SetDishList", RequestNamespace="http://coffeemania.ru/VPiskov", ResponseNamespace="http://coffeemania.ru/VPiskov", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetDishList([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] DishN[] ListOfDish) {
            this.Invoke("SetDishList", new object[] {
                        ListOfDish});
        }
        
        /// <remarks/>
        public void SetDishListAsync(DishN[] ListOfDish) {
            this.SetDishListAsync(ListOfDish, null);
        }
        
        /// <remarks/>
        public void SetDishListAsync(DishN[] ListOfDish, object userState) {
            if ((this.SetDishListOperationCompleted == null)) {
                this.SetDishListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetDishListOperationCompleted);
            }
            this.InvokeAsync("SetDishList", new object[] {
                        ListOfDish}, this.SetDishListOperationCompleted, userState);
        }
        
        private void OnSetDishListOperationCompleted(object arg) {
            if ((this.SetDishListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetDishListCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://coffeemania.ru/VPiskov/SeтMnuToServer", RequestNamespace="http://coffeemania.ru/VPiskov", ResponseNamespace="http://coffeemania.ru/VPiskov", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SeтMnuToServer(AlohaMnu Mnu) {
            this.Invoke("SeтMnuToServer", new object[] {
                        Mnu});
        }
        
        /// <remarks/>
        public void SeтMnuToServerAsync(AlohaMnu Mnu) {
            this.SeтMnuToServerAsync(Mnu, null);
        }
        
        /// <remarks/>
        public void SeтMnuToServerAsync(AlohaMnu Mnu, object userState) {
            if ((this.SeтMnuToServerOperationCompleted == null)) {
                this.SeтMnuToServerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeтMnuToServerOperationCompleted);
            }
            this.InvokeAsync("SeтMnuToServer", new object[] {
                        Mnu}, this.SeтMnuToServerOperationCompleted, userState);
        }
        
        private void OnSeтMnuToServerOperationCompleted(object arg) {
            if ((this.SeтMnuToServerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SeтMnuToServerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://coffeemania.ru/VPiskov/SetMnuToServer", RequestNamespace="http://coffeemania.ru/VPiskov", ResponseNamespace="http://coffeemania.ru/VPiskov", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetMnuToServer(AlohaMnu Mnu) {
            this.Invoke("SetMnuToServer", new object[] {
                        Mnu});
        }
        
        /// <remarks/>
        public void SetMnuToServerAsync(AlohaMnu Mnu) {
            this.SetMnuToServerAsync(Mnu, null);
        }
        
        /// <remarks/>
        public void SetMnuToServerAsync(AlohaMnu Mnu, object userState) {
            if ((this.SetMnuToServerOperationCompleted == null)) {
                this.SetMnuToServerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetMnuToServerOperationCompleted);
            }
            this.InvokeAsync("SetMnuToServer", new object[] {
                        Mnu}, this.SetMnuToServerOperationCompleted, userState);
        }
        
        private void OnSetMnuToServerOperationCompleted(object arg) {
            if ((this.SetMnuToServerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetMnuToServerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coffeemania.ru/VPiskov")]
    public enum AlohaEventType {
        
        /// <remarks/>
        Login,
        
        /// <remarks/>
        LogOut,
        
        /// <remarks/>
        TransferTable,
        
        /// <remarks/>
        TErmInit,
        
        /// <remarks/>
        PrintPredCheck,
        
        /// <remarks/>
        CloseCheck,
        
        /// <remarks/>
        LoyaltyTimeOutError,
        
        /// <remarks/>
        LoyaltyOtherError,
        
        /// <remarks/>
        LoyaltyCardOk,
        
        /// <remarks/>
        ErrorCreditCardterminal,
        
        /// <remarks/>
        AndrFoool,
        
        /// <remarks/>
        AndrFoool2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coffeemania.ru/VPiskov")]
    public partial class StopListReasonT {
        
        private string nameField;
        
        private string descriptionField;
        
        private long typeNumField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public long TypeNum {
            get {
                return this.typeNumField;
            }
            set {
                this.typeNumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coffeemania.ru/VPiskov")]
    public partial class AlohaCategory {
        
        private string nameField;
        
        private int idField;
        
        private int depField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int Dep {
            get {
                return this.depField;
            }
            set {
                this.depField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coffeemania.ru/VPiskov")]
    public partial class AlohaMod {
        
        private int barCodeField;
        
        private string nameField;
        
        private decimal priceField;
        
        /// <remarks/>
        public int BarCode {
            get {
                return this.barCodeField;
            }
            set {
                this.barCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coffeemania.ru/VPiskov")]
    public partial class AlohaModGroupe {
        
        private int idField;
        
        private string nameField;
        
        private AlohaMod[] modsField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AlohaMod[] Mods {
            get {
                return this.modsField;
            }
            set {
                this.modsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coffeemania.ru/VPiskov")]
    public partial class AlohaDish {
        
        private decimal priceField;
        
        private int depField;
        
        private int barCodeField;
        
        private int delayField;
        
        private int oneCategoryField;
        
        private int[] categoriesField;
        
        private string nameField;
        
        private string engNameField;
        
        private AlohaModGroupe[] modGroupsField;
        
        /// <remarks/>
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public int Dep {
            get {
                return this.depField;
            }
            set {
                this.depField = value;
            }
        }
        
        /// <remarks/>
        public int BarCode {
            get {
                return this.barCodeField;
            }
            set {
                this.barCodeField = value;
            }
        }
        
        /// <remarks/>
        public int delay {
            get {
                return this.delayField;
            }
            set {
                this.delayField = value;
            }
        }
        
        /// <remarks/>
        public int OneCategory {
            get {
                return this.oneCategoryField;
            }
            set {
                this.oneCategoryField = value;
            }
        }
        
        /// <remarks/>
        public int[] Categories {
            get {
                return this.categoriesField;
            }
            set {
                this.categoriesField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string EngName {
            get {
                return this.engNameField;
            }
            set {
                this.engNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AlohaModGroupe[] ModGroups {
            get {
                return this.modGroupsField;
            }
            set {
                this.modGroupsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coffeemania.ru/VPiskov")]
    public partial class AlohaSMnu {
        
        private int idField;
        
        private string nameField;
        
        private int depField;
        
        private AlohaDish[] dishesField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int Dep {
            get {
                return this.depField;
            }
            set {
                this.depField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AlohaDish[] Dishes {
            get {
                return this.dishesField;
            }
            set {
                this.dishesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coffeemania.ru/VPiskov")]
    public partial class AlohaMnu {
        
        private int idField;
        
        private AlohaSMnu[] smnusField;
        
        private int depField;
        
        private string nameField;
        
        private AlohaCategory[] catsField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public AlohaSMnu[] Smnus {
            get {
                return this.smnusField;
            }
            set {
                this.smnusField = value;
            }
        }
        
        /// <remarks/>
        public int Dep {
            get {
                return this.depField;
            }
            set {
                this.depField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AlohaCategory[] Cats {
            get {
                return this.catsField;
            }
            set {
                this.catsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coffeemania.ru/VPiskov")]
    public partial class DishN {
        
        private string nameField;
        
        private long barCodeField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public long BarCode {
            get {
                return this.barCodeField;
            }
            set {
                this.barCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coffeemania.ru/VPiskov")]
    public partial class StopListReasonEvent {
        
        private int depField;
        
        private string depNameField;
        
        private int barCodeField;
        
        private long typeNumField;
        
        private System.DateTime rDateTimeField;
        
        /// <remarks/>
        public int Dep {
            get {
                return this.depField;
            }
            set {
                this.depField = value;
            }
        }
        
        /// <remarks/>
        public string DepName {
            get {
                return this.depNameField;
            }
            set {
                this.depNameField = value;
            }
        }
        
        /// <remarks/>
        public int BarCode {
            get {
                return this.barCodeField;
            }
            set {
                this.barCodeField = value;
            }
        }
        
        /// <remarks/>
        public long TypeNum {
            get {
                return this.typeNumField;
            }
            set {
                this.typeNumField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RDateTime {
            get {
                return this.rDateTimeField;
            }
            set {
                this.rDateTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coffeemania.ru/VPiskov")]
    public enum RemoteEventType {
        
        /// <remarks/>
        AndrFoool,
        
        /// <remarks/>
        CheckClosed,
        
        /// <remarks/>
        TermActive,
        
        /// <remarks/>
        AlohaInit,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void MenuModifEnabledCompletedEventHandler(object sender, MenuModifEnabledCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MenuModifEnabledCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MenuModifEnabledCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void SendGloryLogCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetGloryLogCompletedEventHandler(object sender, GetGloryLogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGloryLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGloryLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetEventCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void AlohaEventSendCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void AlohaEventSend2CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetResonTypesCompletedEventHandler(object sender, GetResonTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetResonTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetResonTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StopListReasonT[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StopListReasonT[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void RemoteEventSendCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetCurentResonsCompletedEventHandler(object sender, GetCurentResonsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCurentResonsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCurentResonsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StopListReasonEvent[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StopListReasonEvent[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Error {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void AddStopListReasonsCompletedEventHandler(object sender, AddStopListReasonsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddStopListReasonsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddStopListReasonsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ErrorMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void SetDishListCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void SeтMnuToServerCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void SetMnuToServerCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591