//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDiscountCard.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vfiliasesb0:2580/process/WriteVisitProc")]
        public string PDiscountCard_vfiliasesb0_WriteVisitDiscountService {
            get {
                return ((string)(this["PDiscountCard_vfiliasesb0_WriteVisitDiscountService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://s2010:3132/Service1.asmx")]
        public string PDiscountCard_s2010_Service1 {
            get {
                return ((string)(this["PDiscountCard_s2010_Service1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://s2010:3131/Service1.asmx")]
        public string PDiscountCard_StopListService_Service1 {
            get {
                return ((string)(this["PDiscountCard_StopListService_Service1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://s2010:3131/Service1.asmx")]
        public string PDiscountCard_sadkudr1_Service1 {
            get {
                return ((string)(this["PDiscountCard_sadkudr1_Service1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=avrora1\\sqlexpress;Initial Catalog=AlohaToGo;Persist Security Info=Tr" +
            "ue;User ID=PDiscount;Password=PDiscount")]
        public string AlohaToGoConnectionString {
            get {
                return ((string)(this["AlohaToGoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=s2010;Initial Catalog=AlohaPDiscount;User ID=v.piskov")]
        public string AlohaPDiscountConnectionString {
            get {
                return ((string)(this["AlohaPDiscountConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=s2010;Initial Catalog=AlohaPDiscount;User ID=v.piskov;Password=Eit160" +
            "t")]
        public string AlohaPDiscountConnectionString1 {
            get {
                return ((string)(this["AlohaPDiscountConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://s2010:3134/service1.asmx")]
        public string PDiscountCard_ZRSrv_Service1 {
            get {
                return ((string)(this["PDiscountCard_ZRSrv_Service1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ams01-sv113.ams01-aloha.local:8080/StoredValue/public/soap/StoredValuePubl" +
            "icWS")]
        public string PDiscountCard_ASVWebSrv_StoredValuePublicWSImplService {
            get {
                return ((string)(this["PDiscountCard_ASVWebSrv_StoredValuePublicWSImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://server1c/alco/ws/wsAlco.1cws")]
        public string PDiscountCard_EGAISSrv_wsExtAlco_WebServiceAlco {
            get {
                return ((string)(this["PDiscountCard_EGAISSrv_wsExtAlco_WebServiceAlco"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://server1c/retail/ws/wsAlco.1cws")]
        public string PDiscountCard_EGAISSrv2_wsExtAlco_WebServiceAlco {
            get {
                return ((string)(this["PDiscountCard_EGAISSrv2_wsExtAlco_WebServiceAlco"]));
            }
        }
    }
}
