//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3603.
// 
#pragma warning disable 1591
/*
namespace PDiscountCard.StopListService
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "Service1Soap", Namespace = "http://coffeemania.ru/VPiskov")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback GetEventOperationCompleted;

        private System.Threading.SendOrPostCallback TaskListRunOperationCompleted;

        private System.Threading.SendOrPostCallback SetDishListOperationCompleted;

        private bool useDefaultCredentialsSetExplicitly;

        /// <remarks/>
        public Service1()
        {
           // this.Url = global::PDiscountCard.Properties.Settings.Default.PDiscountCard_StopListService_Service1;
            this.Url = @"http://s2010:3131/Service1.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true))
            {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else
            {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        public new string Url
        {
            get
            {
                return base.Url;
            }
            set
            {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true)
                            && (this.useDefaultCredentialsSetExplicitly == false))
                            && (this.IsLocalFileSystemWebService(value) == false)))
                {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }

        public new bool UseDefaultCredentials
        {
            get
            {
                return base.UseDefaultCredentials;
            }
            set
            {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        /// <remarks/>
        public event GetEventCompletedEventHandler GetEventCompleted;

        /// <remarks/>
        public event TaskListRunCompletedEventHandler TaskListRunCompleted;

        /// <remarks/>
        public event SetDishListCompletedEventHandler SetDishListCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://coffeemania.ru/VPiskov/GetEvent", RequestNamespace = "http://coffeemania.ru/VPiskov", ResponseNamespace = "http://coffeemania.ru/VPiskov", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetEvent(int DepNum, long[] DishIds)
        {
            this.Invoke("GetEvent", new object[] {
                        DepNum,
                        DishIds});
        }

        /// <remarks/>
        public void GetEventAsync(int DepNum, long[] DishIds)
        {
            this.GetEventAsync(DepNum, DishIds, null);
        }

        /// <remarks/>
        public void GetEventAsync(int DepNum, long[] DishIds, object userState)
        {
            if ((this.GetEventOperationCompleted == null))
            {
                this.GetEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEventOperationCompleted);
            }
            this.InvokeAsync("GetEvent", new object[] {
                        DepNum,
                        DishIds}, this.GetEventOperationCompleted, userState);
        }

        private void OnGetEventOperationCompleted(object arg)
        {
            if ((this.GetEventCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEventCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://coffeemania.ru/VPiskov/TaskListRun", RequestNamespace = "http://coffeemania.ru/VPiskov", ResponseNamespace = "http://coffeemania.ru/VPiskov", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TaskListRun(string _MashName)
        {
            this.Invoke("TaskListRun", new object[] {
                        _MashName});
        }

        /// <remarks/>
        public void TaskListRunAsync(string _MashName)
        {
            this.TaskListRunAsync(_MashName, null);
        }

        /// <remarks/>
        public void TaskListRunAsync(string _MashName, object userState)
        {
            if ((this.TaskListRunOperationCompleted == null))
            {
                this.TaskListRunOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTaskListRunOperationCompleted);
            }
            this.InvokeAsync("TaskListRun", new object[] {
                        _MashName}, this.TaskListRunOperationCompleted, userState);
        }

        private void OnTaskListRunOperationCompleted(object arg)
        {
            if ((this.TaskListRunCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TaskListRunCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://coffeemania.ru/VPiskov/SetDishList", RequestNamespace = "http://coffeemania.ru/VPiskov", ResponseNamespace = "http://coffeemania.ru/VPiskov", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetDishList([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)] DishN[] ListOfDish)
        {
            this.Invoke("SetDishList", new object[] {
                        ListOfDish});
        }

        /// <remarks/>
        public void SetDishListAsync(DishN[] ListOfDish)
        {
            this.SetDishListAsync(ListOfDish, null);
        }

        /// <remarks/>
        public void SetDishListAsync(DishN[] ListOfDish, object userState)
        {
            if ((this.SetDishListOperationCompleted == null))
            {
                this.SetDishListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetDishListOperationCompleted);
            }
            this.InvokeAsync("SetDishList", new object[] {
                        ListOfDish}, this.SetDishListOperationCompleted, userState);
        }

        private void OnSetDishListOperationCompleted(object arg)
        {
            if ((this.SetDishListCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetDishListCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }

        private bool IsLocalFileSystemWebService(string url)
        {
            if (((url == null)
                        || (url == string.Empty)))
            {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024)
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0)))
            {
                return true;
            }
            return false;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://coffeemania.ru/VPiskov")]
    public partial class DishN
    {

        private string nameField;

        private long barCodeField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public long BarCode
        {
            get
            {
                return this.barCodeField;
            }
            set
            {
                this.barCodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetEventCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void TaskListRunCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void SetDishListCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}
*/
#pragma warning restore 1591