#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDiscountCard.TakeOut
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AlohaToGo")]
	public partial class TOServerBaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGuest(Guest instance);
    partial void UpdateGuest(Guest instance);
    partial void DeleteGuest(Guest instance);
    #endregion
		
		public TOServerBaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TOServerBaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TOServerBaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TOServerBaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Guest> Guests
		{
			get
			{
				return this.GetTable<Guest>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Guest")]
	public partial class Guest : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _GuestID;
		
		private System.Nullable<long> _ReferenceID;
		
		private System.Nullable<long> _MemberlinkID;
		
		private System.Nullable<long> _VipInfoID;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _EmailAddress;
		
		private string _PrimaryPhoneAreaCode;
		
		private string _PrimaryPhoneNumber;
		
		private string _PrimaryPhoneExtension;
		
		private System.Nullable<long> _PrimaryPhoneNumberTypeID;
		
		private string _AddressLine1;
		
		private string _AddressLine2;
		
		private string _City;
		
		private string _State;
		
		private string _Zip;
		
		private string _Country;
		
		private System.Nullable<long> _ZoneID;
		
		private System.Nullable<long> _AddressTypeID;
		
		private System.Nullable<long> _DwellingTypeID;
		
		private string _Company;
		
		private string _AddressNotes;
		
		private System.Nullable<double> _DistanceFromStore;
		
		private System.Nullable<decimal> _OverrideDeliveryFee;
		
		private string _ProfileInfo;
		
		private long _Attributes;
		
		private bool _SmokingPreference;
		
		private System.Nullable<System.DateTime> _BirthdayDate;
		
		private System.Nullable<System.DateTime> _AnniversaryDate;
		
		private string _Notes;
		
		private System.Nullable<int> _OrderHistoryCount;
		
		private System.Nullable<decimal> _OrderHistoryTotal;
		
		private System.Nullable<long> _ContactPhoneNumberID;
		
		private System.Nullable<long> _ContactAddressID;
		
		private System.Nullable<long> _ContactVehicleID;
		
		private string _HouseAccountID;
		
		private System.Nullable<byte> _CreditCardType;
		
		private System.Data.Linq.Binary _CreditCardNumber;
		
		private System.Data.Linq.Binary _CreditCardExpirationDate;
		
		private string _CreditCardNumberMasked;
		
		private string _EFrequencyMemberID;
		
		private string _TaxID;
		
		private System.DateTime _LastActivity;
		
		private bool _IsTraining;
		
		private System.Nullable<int> _LastModifiedReference;
		
		private System.DateTime _LastModifiedTimestamp;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGuestIDChanging(long value);
    partial void OnGuestIDChanged();
    partial void OnReferenceIDChanging(System.Nullable<long> value);
    partial void OnReferenceIDChanged();
    partial void OnMemberlinkIDChanging(System.Nullable<long> value);
    partial void OnMemberlinkIDChanged();
    partial void OnVipInfoIDChanging(System.Nullable<long> value);
    partial void OnVipInfoIDChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnEmailAddressChanging(string value);
    partial void OnEmailAddressChanged();
    partial void OnPrimaryPhoneAreaCodeChanging(string value);
    partial void OnPrimaryPhoneAreaCodeChanged();
    partial void OnPrimaryPhoneNumberChanging(string value);
    partial void OnPrimaryPhoneNumberChanged();
    partial void OnPrimaryPhoneExtensionChanging(string value);
    partial void OnPrimaryPhoneExtensionChanged();
    partial void OnPrimaryPhoneNumberTypeIDChanging(System.Nullable<long> value);
    partial void OnPrimaryPhoneNumberTypeIDChanged();
    partial void OnAddressLine1Changing(string value);
    partial void OnAddressLine1Changed();
    partial void OnAddressLine2Changing(string value);
    partial void OnAddressLine2Changed();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZipChanging(string value);
    partial void OnZipChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnZoneIDChanging(System.Nullable<long> value);
    partial void OnZoneIDChanged();
    partial void OnAddressTypeIDChanging(System.Nullable<long> value);
    partial void OnAddressTypeIDChanged();
    partial void OnDwellingTypeIDChanging(System.Nullable<long> value);
    partial void OnDwellingTypeIDChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnAddressNotesChanging(string value);
    partial void OnAddressNotesChanged();
    partial void OnDistanceFromStoreChanging(System.Nullable<double> value);
    partial void OnDistanceFromStoreChanged();
    partial void OnOverrideDeliveryFeeChanging(System.Nullable<decimal> value);
    partial void OnOverrideDeliveryFeeChanged();
    partial void OnProfileInfoChanging(string value);
    partial void OnProfileInfoChanged();
    partial void OnAttributesChanging(long value);
    partial void OnAttributesChanged();
    partial void OnSmokingPreferenceChanging(bool value);
    partial void OnSmokingPreferenceChanged();
    partial void OnBirthdayDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBirthdayDateChanged();
    partial void OnAnniversaryDateChanging(System.Nullable<System.DateTime> value);
    partial void OnAnniversaryDateChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    partial void OnOrderHistoryCountChanging(System.Nullable<int> value);
    partial void OnOrderHistoryCountChanged();
    partial void OnOrderHistoryTotalChanging(System.Nullable<decimal> value);
    partial void OnOrderHistoryTotalChanged();
    partial void OnContactPhoneNumberIDChanging(System.Nullable<long> value);
    partial void OnContactPhoneNumberIDChanged();
    partial void OnContactAddressIDChanging(System.Nullable<long> value);
    partial void OnContactAddressIDChanged();
    partial void OnContactVehicleIDChanging(System.Nullable<long> value);
    partial void OnContactVehicleIDChanged();
    partial void OnHouseAccountIDChanging(string value);
    partial void OnHouseAccountIDChanged();
    partial void OnCreditCardTypeChanging(System.Nullable<byte> value);
    partial void OnCreditCardTypeChanged();
    partial void OnCreditCardNumberChanging(System.Data.Linq.Binary value);
    partial void OnCreditCardNumberChanged();
    partial void OnCreditCardExpirationDateChanging(System.Data.Linq.Binary value);
    partial void OnCreditCardExpirationDateChanged();
    partial void OnCreditCardNumberMaskedChanging(string value);
    partial void OnCreditCardNumberMaskedChanged();
    partial void OnEFrequencyMemberIDChanging(string value);
    partial void OnEFrequencyMemberIDChanged();
    partial void OnTaxIDChanging(string value);
    partial void OnTaxIDChanged();
    partial void OnLastActivityChanging(System.DateTime value);
    partial void OnLastActivityChanged();
    partial void OnIsTrainingChanging(bool value);
    partial void OnIsTrainingChanged();
    partial void OnLastModifiedReferenceChanging(System.Nullable<int> value);
    partial void OnLastModifiedReferenceChanged();
    partial void OnLastModifiedTimestampChanging(System.DateTime value);
    partial void OnLastModifiedTimestampChanged();
    #endregion
		
		public Guest()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long GuestID
		{
			get
			{
				return this._GuestID;
			}
			set
			{
				if ((this._GuestID != value))
				{
					this.OnGuestIDChanging(value);
					this.SendPropertyChanging();
					this._GuestID = value;
					this.SendPropertyChanged("GuestID");
					this.OnGuestIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferenceID", DbType="BigInt")]
		public System.Nullable<long> ReferenceID
		{
			get
			{
				return this._ReferenceID;
			}
			set
			{
				if ((this._ReferenceID != value))
				{
					this.OnReferenceIDChanging(value);
					this.SendPropertyChanging();
					this._ReferenceID = value;
					this.SendPropertyChanged("ReferenceID");
					this.OnReferenceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberlinkID", DbType="BigInt")]
		public System.Nullable<long> MemberlinkID
		{
			get
			{
				return this._MemberlinkID;
			}
			set
			{
				if ((this._MemberlinkID != value))
				{
					this.OnMemberlinkIDChanging(value);
					this.SendPropertyChanging();
					this._MemberlinkID = value;
					this.SendPropertyChanged("MemberlinkID");
					this.OnMemberlinkIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VipInfoID", DbType="BigInt")]
		public System.Nullable<long> VipInfoID
		{
			get
			{
				return this._VipInfoID;
			}
			set
			{
				if ((this._VipInfoID != value))
				{
					this.OnVipInfoIDChanging(value);
					this.SendPropertyChanging();
					this._VipInfoID = value;
					this.SendPropertyChanged("VipInfoID");
					this.OnVipInfoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(30)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(30)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="NVarChar(50)")]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this.OnEmailAddressChanging(value);
					this.SendPropertyChanging();
					this._EmailAddress = value;
					this.SendPropertyChanged("EmailAddress");
					this.OnEmailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryPhoneAreaCode", DbType="NVarChar(7)")]
		public string PrimaryPhoneAreaCode
		{
			get
			{
				return this._PrimaryPhoneAreaCode;
			}
			set
			{
				if ((this._PrimaryPhoneAreaCode != value))
				{
					this.OnPrimaryPhoneAreaCodeChanging(value);
					this.SendPropertyChanging();
					this._PrimaryPhoneAreaCode = value;
					this.SendPropertyChanged("PrimaryPhoneAreaCode");
					this.OnPrimaryPhoneAreaCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryPhoneNumber", DbType="NVarChar(15)")]
		public string PrimaryPhoneNumber
		{
			get
			{
				return this._PrimaryPhoneNumber;
			}
			set
			{
				if ((this._PrimaryPhoneNumber != value))
				{
					this.OnPrimaryPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PrimaryPhoneNumber = value;
					this.SendPropertyChanged("PrimaryPhoneNumber");
					this.OnPrimaryPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryPhoneExtension", DbType="NVarChar(5)")]
		public string PrimaryPhoneExtension
		{
			get
			{
				return this._PrimaryPhoneExtension;
			}
			set
			{
				if ((this._PrimaryPhoneExtension != value))
				{
					this.OnPrimaryPhoneExtensionChanging(value);
					this.SendPropertyChanging();
					this._PrimaryPhoneExtension = value;
					this.SendPropertyChanged("PrimaryPhoneExtension");
					this.OnPrimaryPhoneExtensionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryPhoneNumberTypeID", DbType="BigInt")]
		public System.Nullable<long> PrimaryPhoneNumberTypeID
		{
			get
			{
				return this._PrimaryPhoneNumberTypeID;
			}
			set
			{
				if ((this._PrimaryPhoneNumberTypeID != value))
				{
					this.OnPrimaryPhoneNumberTypeIDChanging(value);
					this.SendPropertyChanging();
					this._PrimaryPhoneNumberTypeID = value;
					this.SendPropertyChanged("PrimaryPhoneNumberTypeID");
					this.OnPrimaryPhoneNumberTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressLine1", DbType="NVarChar(50)")]
		public string AddressLine1
		{
			get
			{
				return this._AddressLine1;
			}
			set
			{
				if ((this._AddressLine1 != value))
				{
					this.OnAddressLine1Changing(value);
					this.SendPropertyChanging();
					this._AddressLine1 = value;
					this.SendPropertyChanged("AddressLine1");
					this.OnAddressLine1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressLine2", DbType="NVarChar(50)")]
		public string AddressLine2
		{
			get
			{
				return this._AddressLine2;
			}
			set
			{
				if ((this._AddressLine2 != value))
				{
					this.OnAddressLine2Changing(value);
					this.SendPropertyChanging();
					this._AddressLine2 = value;
					this.SendPropertyChanged("AddressLine2");
					this.OnAddressLine2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(30)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(30)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="NVarChar(20)")]
		public string Zip
		{
			get
			{
				return this._Zip;
			}
			set
			{
				if ((this._Zip != value))
				{
					this.OnZipChanging(value);
					this.SendPropertyChanging();
					this._Zip = value;
					this.SendPropertyChanged("Zip");
					this.OnZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(30)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZoneID", DbType="BigInt")]
		public System.Nullable<long> ZoneID
		{
			get
			{
				return this._ZoneID;
			}
			set
			{
				if ((this._ZoneID != value))
				{
					this.OnZoneIDChanging(value);
					this.SendPropertyChanging();
					this._ZoneID = value;
					this.SendPropertyChanged("ZoneID");
					this.OnZoneIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressTypeID", DbType="BigInt")]
		public System.Nullable<long> AddressTypeID
		{
			get
			{
				return this._AddressTypeID;
			}
			set
			{
				if ((this._AddressTypeID != value))
				{
					this.OnAddressTypeIDChanging(value);
					this.SendPropertyChanging();
					this._AddressTypeID = value;
					this.SendPropertyChanged("AddressTypeID");
					this.OnAddressTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DwellingTypeID", DbType="BigInt")]
		public System.Nullable<long> DwellingTypeID
		{
			get
			{
				return this._DwellingTypeID;
			}
			set
			{
				if ((this._DwellingTypeID != value))
				{
					this.OnDwellingTypeIDChanging(value);
					this.SendPropertyChanging();
					this._DwellingTypeID = value;
					this.SendPropertyChanged("DwellingTypeID");
					this.OnDwellingTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="NVarChar(50)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressNotes", DbType="NVarChar(MAX)")]
		public string AddressNotes
		{
			get
			{
				return this._AddressNotes;
			}
			set
			{
				if ((this._AddressNotes != value))
				{
					this.OnAddressNotesChanging(value);
					this.SendPropertyChanging();
					this._AddressNotes = value;
					this.SendPropertyChanged("AddressNotes");
					this.OnAddressNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistanceFromStore", DbType="Float")]
		public System.Nullable<double> DistanceFromStore
		{
			get
			{
				return this._DistanceFromStore;
			}
			set
			{
				if ((this._DistanceFromStore != value))
				{
					this.OnDistanceFromStoreChanging(value);
					this.SendPropertyChanging();
					this._DistanceFromStore = value;
					this.SendPropertyChanged("DistanceFromStore");
					this.OnDistanceFromStoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OverrideDeliveryFee", DbType="Money")]
		public System.Nullable<decimal> OverrideDeliveryFee
		{
			get
			{
				return this._OverrideDeliveryFee;
			}
			set
			{
				if ((this._OverrideDeliveryFee != value))
				{
					this.OnOverrideDeliveryFeeChanging(value);
					this.SendPropertyChanging();
					this._OverrideDeliveryFee = value;
					this.SendPropertyChanged("OverrideDeliveryFee");
					this.OnOverrideDeliveryFeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfileInfo", DbType="NVarChar(MAX)")]
		public string ProfileInfo
		{
			get
			{
				return this._ProfileInfo;
			}
			set
			{
				if ((this._ProfileInfo != value))
				{
					this.OnProfileInfoChanging(value);
					this.SendPropertyChanging();
					this._ProfileInfo = value;
					this.SendPropertyChanged("ProfileInfo");
					this.OnProfileInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attributes", DbType="BigInt NOT NULL")]
		public long Attributes
		{
			get
			{
				return this._Attributes;
			}
			set
			{
				if ((this._Attributes != value))
				{
					this.OnAttributesChanging(value);
					this.SendPropertyChanging();
					this._Attributes = value;
					this.SendPropertyChanged("Attributes");
					this.OnAttributesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmokingPreference", DbType="Bit NOT NULL")]
		public bool SmokingPreference
		{
			get
			{
				return this._SmokingPreference;
			}
			set
			{
				if ((this._SmokingPreference != value))
				{
					this.OnSmokingPreferenceChanging(value);
					this.SendPropertyChanging();
					this._SmokingPreference = value;
					this.SendPropertyChanged("SmokingPreference");
					this.OnSmokingPreferenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirthdayDate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> BirthdayDate
		{
			get
			{
				return this._BirthdayDate;
			}
			set
			{
				if ((this._BirthdayDate != value))
				{
					this.OnBirthdayDateChanging(value);
					this.SendPropertyChanging();
					this._BirthdayDate = value;
					this.SendPropertyChanged("BirthdayDate");
					this.OnBirthdayDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnniversaryDate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> AnniversaryDate
		{
			get
			{
				return this._AnniversaryDate;
			}
			set
			{
				if ((this._AnniversaryDate != value))
				{
					this.OnAnniversaryDateChanging(value);
					this.SendPropertyChanging();
					this._AnniversaryDate = value;
					this.SendPropertyChanged("AnniversaryDate");
					this.OnAnniversaryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(MAX)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderHistoryCount", DbType="Int")]
		public System.Nullable<int> OrderHistoryCount
		{
			get
			{
				return this._OrderHistoryCount;
			}
			set
			{
				if ((this._OrderHistoryCount != value))
				{
					this.OnOrderHistoryCountChanging(value);
					this.SendPropertyChanging();
					this._OrderHistoryCount = value;
					this.SendPropertyChanged("OrderHistoryCount");
					this.OnOrderHistoryCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderHistoryTotal", DbType="Money")]
		public System.Nullable<decimal> OrderHistoryTotal
		{
			get
			{
				return this._OrderHistoryTotal;
			}
			set
			{
				if ((this._OrderHistoryTotal != value))
				{
					this.OnOrderHistoryTotalChanging(value);
					this.SendPropertyChanging();
					this._OrderHistoryTotal = value;
					this.SendPropertyChanged("OrderHistoryTotal");
					this.OnOrderHistoryTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPhoneNumberID", DbType="BigInt")]
		public System.Nullable<long> ContactPhoneNumberID
		{
			get
			{
				return this._ContactPhoneNumberID;
			}
			set
			{
				if ((this._ContactPhoneNumberID != value))
				{
					this.OnContactPhoneNumberIDChanging(value);
					this.SendPropertyChanging();
					this._ContactPhoneNumberID = value;
					this.SendPropertyChanged("ContactPhoneNumberID");
					this.OnContactPhoneNumberIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactAddressID", DbType="BigInt")]
		public System.Nullable<long> ContactAddressID
		{
			get
			{
				return this._ContactAddressID;
			}
			set
			{
				if ((this._ContactAddressID != value))
				{
					this.OnContactAddressIDChanging(value);
					this.SendPropertyChanging();
					this._ContactAddressID = value;
					this.SendPropertyChanged("ContactAddressID");
					this.OnContactAddressIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactVehicleID", DbType="BigInt")]
		public System.Nullable<long> ContactVehicleID
		{
			get
			{
				return this._ContactVehicleID;
			}
			set
			{
				if ((this._ContactVehicleID != value))
				{
					this.OnContactVehicleIDChanging(value);
					this.SendPropertyChanging();
					this._ContactVehicleID = value;
					this.SendPropertyChanged("ContactVehicleID");
					this.OnContactVehicleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HouseAccountID", DbType="NVarChar(50)")]
		public string HouseAccountID
		{
			get
			{
				return this._HouseAccountID;
			}
			set
			{
				if ((this._HouseAccountID != value))
				{
					this.OnHouseAccountIDChanging(value);
					this.SendPropertyChanging();
					this._HouseAccountID = value;
					this.SendPropertyChanged("HouseAccountID");
					this.OnHouseAccountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditCardType", DbType="TinyInt")]
		public System.Nullable<byte> CreditCardType
		{
			get
			{
				return this._CreditCardType;
			}
			set
			{
				if ((this._CreditCardType != value))
				{
					this.OnCreditCardTypeChanging(value);
					this.SendPropertyChanging();
					this._CreditCardType = value;
					this.SendPropertyChanged("CreditCardType");
					this.OnCreditCardTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditCardNumber", DbType="VarBinary(64)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary CreditCardNumber
		{
			get
			{
				return this._CreditCardNumber;
			}
			set
			{
				if ((this._CreditCardNumber != value))
				{
					this.OnCreditCardNumberChanging(value);
					this.SendPropertyChanging();
					this._CreditCardNumber = value;
					this.SendPropertyChanged("CreditCardNumber");
					this.OnCreditCardNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditCardExpirationDate", DbType="VarBinary(64)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary CreditCardExpirationDate
		{
			get
			{
				return this._CreditCardExpirationDate;
			}
			set
			{
				if ((this._CreditCardExpirationDate != value))
				{
					this.OnCreditCardExpirationDateChanging(value);
					this.SendPropertyChanging();
					this._CreditCardExpirationDate = value;
					this.SendPropertyChanged("CreditCardExpirationDate");
					this.OnCreditCardExpirationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditCardNumberMasked", DbType="NVarChar(50)")]
		public string CreditCardNumberMasked
		{
			get
			{
				return this._CreditCardNumberMasked;
			}
			set
			{
				if ((this._CreditCardNumberMasked != value))
				{
					this.OnCreditCardNumberMaskedChanging(value);
					this.SendPropertyChanging();
					this._CreditCardNumberMasked = value;
					this.SendPropertyChanged("CreditCardNumberMasked");
					this.OnCreditCardNumberMaskedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EFrequencyMemberID", DbType="NVarChar(50)")]
		public string EFrequencyMemberID
		{
			get
			{
				return this._EFrequencyMemberID;
			}
			set
			{
				if ((this._EFrequencyMemberID != value))
				{
					this.OnEFrequencyMemberIDChanging(value);
					this.SendPropertyChanging();
					this._EFrequencyMemberID = value;
					this.SendPropertyChanged("EFrequencyMemberID");
					this.OnEFrequencyMemberIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxID", DbType="NVarChar(20)")]
		public string TaxID
		{
			get
			{
				return this._TaxID;
			}
			set
			{
				if ((this._TaxID != value))
				{
					this.OnTaxIDChanging(value);
					this.SendPropertyChanging();
					this._TaxID = value;
					this.SendPropertyChanged("TaxID");
					this.OnTaxIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastActivity", DbType="DateTime NOT NULL")]
		public System.DateTime LastActivity
		{
			get
			{
				return this._LastActivity;
			}
			set
			{
				if ((this._LastActivity != value))
				{
					this.OnLastActivityChanging(value);
					this.SendPropertyChanging();
					this._LastActivity = value;
					this.SendPropertyChanged("LastActivity");
					this.OnLastActivityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsTraining", DbType="Bit NOT NULL")]
		public bool IsTraining
		{
			get
			{
				return this._IsTraining;
			}
			set
			{
				if ((this._IsTraining != value))
				{
					this.OnIsTrainingChanging(value);
					this.SendPropertyChanging();
					this._IsTraining = value;
					this.SendPropertyChanged("IsTraining");
					this.OnIsTrainingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedReference", DbType="Int")]
		public System.Nullable<int> LastModifiedReference
		{
			get
			{
				return this._LastModifiedReference;
			}
			set
			{
				if ((this._LastModifiedReference != value))
				{
					this.OnLastModifiedReferenceChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedReference = value;
					this.SendPropertyChanged("LastModifiedReference");
					this.OnLastModifiedReferenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedTimestamp", DbType="DateTime NOT NULL")]
		public System.DateTime LastModifiedTimestamp
		{
			get
			{
				return this._LastModifiedTimestamp;
			}
			set
			{
				if ((this._LastModifiedTimestamp != value))
				{
					this.OnLastModifiedTimestampChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedTimestamp = value;
					this.SendPropertyChanged("LastModifiedTimestamp");
					this.OnLastModifiedTimestampChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
