//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PDiscountCard.RemoteOrderSrv {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="PiskovSRv")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DishOnStopOperationCompleted;
        
        private System.Threading.SendOrPostCallback OrderOrderedOperationCompleted;
        
        private System.Threading.SendOrPostCallback OrderOrdered2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNewOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetOrderOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::PDiscountCard.Properties.Settings.Default.PDiscountCard_s2010_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DishOnStopCompletedEventHandler DishOnStopCompleted;
        
        /// <remarks/>
        public event OrderOrderedCompletedEventHandler OrderOrderedCompleted;
        
        /// <remarks/>
        public event OrderOrdered2CompletedEventHandler OrderOrdered2Completed;
        
        /// <remarks/>
        public event GetNewOrdersCompletedEventHandler GetNewOrdersCompleted;
        
        /// <remarks/>
        public event SetOrderCompletedEventHandler SetOrderCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("PiskovSRv/DishOnStop", RequestNamespace="PiskovSRv", ResponseNamespace="PiskovSRv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DishOnStop(int DepNum, int BarCode) {
            object[] results = this.Invoke("DishOnStop", new object[] {
                        DepNum,
                        BarCode});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DishOnStopAsync(int DepNum, int BarCode) {
            this.DishOnStopAsync(DepNum, BarCode, null);
        }
        
        /// <remarks/>
        public void DishOnStopAsync(int DepNum, int BarCode, object userState) {
            if ((this.DishOnStopOperationCompleted == null)) {
                this.DishOnStopOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDishOnStopOperationCompleted);
            }
            this.InvokeAsync("DishOnStop", new object[] {
                        DepNum,
                        BarCode}, this.DishOnStopOperationCompleted, userState);
        }
        
        private void OnDishOnStopOperationCompleted(object arg) {
            if ((this.DishOnStopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DishOnStopCompleted(this, new DishOnStopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("PiskovSRv/OrderOrdered", RequestNamespace="PiskovSRv", ResponseNamespace="PiskovSRv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void OrderOrdered(int DepNum, int Id) {
            this.Invoke("OrderOrdered", new object[] {
                        DepNum,
                        Id});
        }
        
        /// <remarks/>
        public void OrderOrderedAsync(int DepNum, int Id) {
            this.OrderOrderedAsync(DepNum, Id, null);
        }
        
        /// <remarks/>
        public void OrderOrderedAsync(int DepNum, int Id, object userState) {
            if ((this.OrderOrderedOperationCompleted == null)) {
                this.OrderOrderedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrderOrderedOperationCompleted);
            }
            this.InvokeAsync("OrderOrdered", new object[] {
                        DepNum,
                        Id}, this.OrderOrderedOperationCompleted, userState);
        }
        
        private void OnOrderOrderedOperationCompleted(object arg) {
            if ((this.OrderOrderedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OrderOrderedCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("PiskovSRv/OrderOrdered2", RequestNamespace="PiskovSRv", ResponseNamespace="PiskovSRv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void OrderOrdered2(int DepNum, string OrderId) {
            this.Invoke("OrderOrdered2", new object[] {
                        DepNum,
                        OrderId});
        }
        
        /// <remarks/>
        public void OrderOrdered2Async(int DepNum, string OrderId) {
            this.OrderOrdered2Async(DepNum, OrderId, null);
        }
        
        /// <remarks/>
        public void OrderOrdered2Async(int DepNum, string OrderId, object userState) {
            if ((this.OrderOrdered2OperationCompleted == null)) {
                this.OrderOrdered2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrderOrdered2OperationCompleted);
            }
            this.InvokeAsync("OrderOrdered2", new object[] {
                        DepNum,
                        OrderId}, this.OrderOrdered2OperationCompleted, userState);
        }
        
        private void OnOrderOrdered2OperationCompleted(object arg) {
            if ((this.OrderOrdered2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OrderOrdered2Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("PiskovSRv/GetNewOrders", RequestNamespace="PiskovSRv", ResponseNamespace="PiskovSRv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrderInfoForAloha[] GetNewOrders(int DepNum, out string selstr) {
            object[] results = this.Invoke("GetNewOrders", new object[] {
                        DepNum});
            selstr = ((string)(results[1]));
            return ((OrderInfoForAloha[])(results[0]));
        }
        
        /// <remarks/>
        public void GetNewOrdersAsync(int DepNum) {
            this.GetNewOrdersAsync(DepNum, null);
        }
        
        /// <remarks/>
        public void GetNewOrdersAsync(int DepNum, object userState) {
            if ((this.GetNewOrdersOperationCompleted == null)) {
                this.GetNewOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNewOrdersOperationCompleted);
            }
            this.InvokeAsync("GetNewOrders", new object[] {
                        DepNum}, this.GetNewOrdersOperationCompleted, userState);
        }
        
        private void OnGetNewOrdersOperationCompleted(object arg) {
            if ((this.GetNewOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNewOrdersCompleted(this, new GetNewOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("PiskovSRv/SetOrder", RequestNamespace="PiskovSRv", ResponseNamespace="PiskovSRv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrderInfoResponse SetOrder(OrderInfo Ch) {
            object[] results = this.Invoke("SetOrder", new object[] {
                        Ch});
            return ((OrderInfoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SetOrderAsync(OrderInfo Ch) {
            this.SetOrderAsync(Ch, null);
        }
        
        /// <remarks/>
        public void SetOrderAsync(OrderInfo Ch, object userState) {
            if ((this.SetOrderOperationCompleted == null)) {
                this.SetOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetOrderOperationCompleted);
            }
            this.InvokeAsync("SetOrder", new object[] {
                        Ch}, this.SetOrderOperationCompleted, userState);
        }
        
        private void OnSetOrderOperationCompleted(object arg) {
            if ((this.SetOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetOrderCompleted(this, new SetOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PiskovSRv")]
    public partial class OrderInfoForAloha {
        
        private int idField;
        
        private string orderIDField;
        
        private int orderDestinationDeptIDField;
        
        private int customerIDField;
        
        private string customerNameField;
        
        private string customerPhoneField;
        
        private System.DateTime orderRegisteredAtTimeField;
        
        private System.DateTime orderRequiredStartTimeField;
        
        private System.DateTime orderRequiredEndTimeField;
        
        private Item[] itemsField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string OrderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
            }
        }
        
        /// <remarks/>
        public int OrderDestinationDeptID {
            get {
                return this.orderDestinationDeptIDField;
            }
            set {
                this.orderDestinationDeptIDField = value;
            }
        }
        
        /// <remarks/>
        public int CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerPhone {
            get {
                return this.customerPhoneField;
            }
            set {
                this.customerPhoneField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OrderRegisteredAtTime {
            get {
                return this.orderRegisteredAtTimeField;
            }
            set {
                this.orderRegisteredAtTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OrderRequiredStartTime {
            get {
                return this.orderRequiredStartTimeField;
            }
            set {
                this.orderRequiredStartTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OrderRequiredEndTime {
            get {
                return this.orderRequiredEndTimeField;
            }
            set {
                this.orderRequiredEndTimeField = value;
            }
        }
        
        /// <remarks/>
        public Item[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PiskovSRv")]
    public partial class Item {
        
        private int itemIDField;
        
        private string itemNameField;
        
        private int itemQuantityField;
        
        private string itemSpecialMessageField;
        
        private Modifier[] modifiersField;
        
        /// <remarks/>
        public int ItemID {
            get {
                return this.itemIDField;
            }
            set {
                this.itemIDField = value;
            }
        }
        
        /// <remarks/>
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        public int ItemQuantity {
            get {
                return this.itemQuantityField;
            }
            set {
                this.itemQuantityField = value;
            }
        }
        
        /// <remarks/>
        public string ItemSpecialMessage {
            get {
                return this.itemSpecialMessageField;
            }
            set {
                this.itemSpecialMessageField = value;
            }
        }
        
        /// <remarks/>
        public Modifier[] Modifiers {
            get {
                return this.modifiersField;
            }
            set {
                this.modifiersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PiskovSRv")]
    public partial class Modifier {
        
        private int itemModifierIDField;
        
        private string itemModifierNameField;
        
        private int itemModifierQuantityField;
        
        private string itemModifierSpecialMessageField;
        
        /// <remarks/>
        public int ItemModifierID {
            get {
                return this.itemModifierIDField;
            }
            set {
                this.itemModifierIDField = value;
            }
        }
        
        /// <remarks/>
        public string ItemModifierName {
            get {
                return this.itemModifierNameField;
            }
            set {
                this.itemModifierNameField = value;
            }
        }
        
        /// <remarks/>
        public int ItemModifierQuantity {
            get {
                return this.itemModifierQuantityField;
            }
            set {
                this.itemModifierQuantityField = value;
            }
        }
        
        /// <remarks/>
        public string ItemModifierSpecialMessage {
            get {
                return this.itemModifierSpecialMessageField;
            }
            set {
                this.itemModifierSpecialMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PiskovSRv")]
    public partial class OrderInfoResponse {
        
        private bool orderInfoIsProcessedField;
        
        private string orderInfoNonFatalErrorMessageField;
        
        /// <remarks/>
        public bool OrderInfoIsProcessed {
            get {
                return this.orderInfoIsProcessedField;
            }
            set {
                this.orderInfoIsProcessedField = value;
            }
        }
        
        /// <remarks/>
        public string OrderInfoNonFatalErrorMessage {
            get {
                return this.orderInfoNonFatalErrorMessageField;
            }
            set {
                this.orderInfoNonFatalErrorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PiskovSRv")]
    public partial class OrderInfo {
        
        private string orderIDField;
        
        private int orderDestinationDeptIDField;
        
        private int customerIDField;
        
        private string customerNameField;
        
        private string customerPhoneField;
        
        private System.DateTime orderRegisteredAtTimeField;
        
        private System.DateTime orderRequiredStartTimeField;
        
        private System.DateTime orderRequiredEndTimeField;
        
        private Item[] itemsField;
        
        /// <remarks/>
        public string OrderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
            }
        }
        
        /// <remarks/>
        public int OrderDestinationDeptID {
            get {
                return this.orderDestinationDeptIDField;
            }
            set {
                this.orderDestinationDeptIDField = value;
            }
        }
        
        /// <remarks/>
        public int CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerPhone {
            get {
                return this.customerPhoneField;
            }
            set {
                this.customerPhoneField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OrderRegisteredAtTime {
            get {
                return this.orderRegisteredAtTimeField;
            }
            set {
                this.orderRegisteredAtTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OrderRequiredStartTime {
            get {
                return this.orderRequiredStartTimeField;
            }
            set {
                this.orderRequiredStartTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OrderRequiredEndTime {
            get {
                return this.orderRequiredEndTimeField;
            }
            set {
                this.orderRequiredEndTimeField = value;
            }
        }
        
        /// <remarks/>
        public Item[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void DishOnStopCompletedEventHandler(object sender, DishOnStopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DishOnStopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DishOnStopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void OrderOrderedCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void OrderOrdered2CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetNewOrdersCompletedEventHandler(object sender, GetNewOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNewOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNewOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderInfoForAloha[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderInfoForAloha[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string selstr {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void SetOrderCompletedEventHandler(object sender, SetOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderInfoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderInfoResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591